---

roles:
  - name: redhat_sap.sap_hostagent
    source: https://galaxy.ansible.com
  - name: redhat_sap.sap_hana_deployment
    source: https://galaxy.ansible.com
  - name: redhat_sap.sap_s4hana_deployment
    source: https://galaxy.ansible.com
  - name: sap-hana-hsr
    src: https://github.com/jjaswanson4/sap-hana-hsr/archive/refs/tags/v1.3.0.tar.gz
  - name: sap-hana-ha-pacemaker
    src: https://github.com/jjaswanson4/sap-hana-ha-pacemaker/archive/refs/tags/v2.0.0.tar.gz

collections:
  - name: redhat_cop.controller_configuration
  - name: community.general
  - name: vmware.vmware_rest
  - name: redhat.rhel_system_roles
  - name: ansible.posix
  - name: awx.awx
  - name: community.vmware
  - name: sap.linux
  - name: jjaswanson4.utilities
  - name: redhat.satellite