---

collections:
  - name: community.general
  - name: vmware.vmware_rest
  - name: redhat.rhel_system_roles
  - name: jjaswanson4.utilities
  - name: jjaswanson4.setup_rhel_for_satellite
  - name: jjaswanson4.install_satellite
    version: '>=1.2.2'
  - name: jjaswanson4.configure_satellite
  - name: ansible.posix
  - name: redhat_cop.controller_configuration
  - name: ansible.controller
  - name: redhat.satellite
  - name: community.vmware
