---

- name: "{{ controller_hostname }}"
  inventory: "{{ asset_prefix }} Infrastructure"
  variables: "{{ lookup('file', controller_configuration_file) | from_yaml }}"
- name: "{{ satellite_hostname }}"
  inventory: "{{ asset_prefix }} Infrastructure"
  variables: "{{ lookup('file', satellite_configuration_file) | from_yaml }}"