---

roles:
  - name: linux-system-roles.cockpit
    source: https://galaxy.ansible.com
  - name: linux-system-roles.metrics
    source: https://galaxy.ansible.com
  - name: redhat_sap.sap_hostagent
    source: https://galaxy.ansible.com
  - name: redhat_sap.sap_hana_deployment
    source: https://galaxy.ansible.com
  - name: redhat_sap.sap_s4hana_deployment
    source: https://galaxy.ansible.com
  - name: sap-hana-hsr
    src: https://github.com/jjaswanson4/sap-hana-hsr/archive/refs/tags/v1.3.0.tar.gz
  - name: sap-hana-ha-pacemaker
    src: https://github.com/jjaswanson4/sap-hana-ha-pacemaker/archive/refs/tags/v2.0.0.tar.gz

collections:
  - name: community.general
  - name: vmware.vmware_rest
  - name: redhat.rhel_system_roles
  - name: jjaswanson4.utilities
    version: '>=1.7.2'
  - name: jjaswanson4.setup_rhel_for_satellite
  - name: jjaswanson4.install_satellite
    version: '>=1.2.4'
  - name: jjaswanson4.configure_satellite
    version: '>=2.1.4'
  - name: ansible.posix
  - name: redhat_cop.controller_configuration
  - name: awx.awx
  - name: redhat.satellite
  - name: community.vmware
  - name: sap.linux