---
ansible_host: 10.15.121.1
ip_address: "{{ ansible_host }}"
cpus: 8
memory_mb: 24576
os: rhel7.9

additional_storage:
  - size_gb: 1000
    scsi_controller: 0
    unit_number: 1
    datastore: storage04-nfs-lun0

selinux_policy: targeted
selinux_state: permissive

config_files:
  - hosts
  - NetworkManager.conf
  - resolv.conf

satellite:
  admin_username: admin
  admin_password: "{{ satellite_password }}"
  version: 6.9
  logical_volumes:
    - name: cache
      size: 20
      path: /var/cache/pulp
    - name: pulp
      size: 500
      path: /var/lib/pulp
    - name: mongodb
      size: 100
      path: /var/lib/mongodb
    - name: qpidd
      size: 20
      path: /var/lib/qpidd
    - name: varlog
      size: 10
      path: /var/log
    - name: pqsql
      size: 100
      path: /var/opt/rh/rh-postgresql12/lib/pgsql
    - name: squid
      size: 10
      path: /var/spool/squid
    - name: usr
      size: 8
      path: /usr
    - name: opt
      size: 8
      path: /opt
    - name: puppetlabs
      size: 1
      path: /opt/puppetlabs
    - name: var
      size: 12
      path: /var
  installer_options:
    - "--foreman-proxy-plugin-remote-execution-ssh-install-key true"
    - "--foreman-proxy-dns true"
  foreman:
    organzations:
      - name: Patching Demo
        initial_organization: yes
    locations:
      - name: Patching Demo
        initial_location: yes
        organizations:
          - name: Patching Demo
    settings:
      - name: default_download_policy
        value: on_demand
      - name: default_proxy_download_policy
        value: on_demand
      - name: unregister_delete_host
        value: true
      - name: entries_per_page
        value: 100
      - name: allow_auto_inventory_upload
        value: yes
      - name: destroy_vm_on_host_delete
        value: yes
    compute_resources:
      - name: vcenter02.lab.msp.redhat.com
        provider: vmware
        provider_params:
          url: vcenter02.lab.msp.redhat.com
          user: 'Administrator@vsphere.local'
          password: "{{ vcenter_password }}"
          datacenter: Patching Demo
        organizations:
          - name: Patching Demo
        locations:
          - name: Patching Demo
    compute_profiles:
      - name: general-vlan146
        compute_resource: vcenter02.lab.msp.redhat.com
        vm_attrs:
          cpus: 4
          corespersocket: 4
          memory_mb: 4096
          firmware: bios
          cluster: General
          resource_pool: Resources
          path: /Datacenters/MSP Lab/vm
          guest_id: rhel7_64Guest
          hardware_version: vmx-13
          memoryHotAddEnabled: 1
          cpuHotAddEnabled: 1
          add_cdrom: 0
          scsi_controllers:
          - type: ParaVirtualSCSIController
            key: 1000
          interfaces_attributes:
            0:
              type: VirtualVmxnet3
              network: dvportgroup-2023
          volumes_attributes:
            0:
              thin: true
              name: Hard disk
              mode: persistent
              controller_key: 1000
              size_gb: 100
              datastore: storage04-nfs-lun0
    domains:
      - name: demo.lab.msp.redhat.com
        organizations:
          - name: Patching Demo
        locations:
          - name: Patching Demo
    subnets:
      - name: VLAN146
        network: 10.15.120.0
        mask: 255.255.252.0
        gateway: 10.15.123.254
        dns_primary: 10.15.121.1
        dns_secondary: 10.15.108.148
        ipam: None
        boot_mode: Static
        organizations:
          - name: Patching Demo
        locations:
          - name: Patching Demo
        domains:
          - name: demo.lab.msp.redhat.com
    hostgroups:
      - name: kickstart-rhel8.1-vlan146
        architecture: x86_64
        compute_profile: general-vlan146
        compute_resource: vcenter02.lab.msp.redhat.com
        content_source: patching-satellite.demo.lab.msp.redhat.com
        content_view: composite-rhel8
        domain: demo.lab.msp.redhat.com
        lifecycle_environment: Production
        operatingsystem: RedHat-8.1
        ptable: RHEL8 Kickstart Partition Table
        organization_of_content_source: Patching Demo
        organizations:
          - Patching Demo
        locations:
          - Patching Demo
        subnet: VLAN146
        parameters:
          - name: "kt_activation_keys"
            value: "ak-rhel8.1-production"
        pxe_loader: None
        root_pass: "{{ ansible_password }}"
        kickstart_repository: Red Hat Enterprise Linux 8 for x86_64 - BaseOS Kickstart 8.1
    partition_tables:
      - name: RHEL8 Kickstart Partition Table
        file: files/rhel8-ptable.erb
        os_family: Redhat
        organizations:
          - name: Patching Demo
        locations:
          - name: Patching Demo
    operating_systems:
      - name: RedHat-8.1.0
        ptable:
          - name: Kickstart default
          - name: RHEL8 Kickstart Partition Table
        update_existing: true
        update_args: --partition-tables "RHEL8 Kickstart Partition Table,Kickstart default"
  katello:
    - organization_name: Patching Demo
      state: present
      manifest: files/manifest.zip
      repo_sync_attempts: 1
      lifecycle_environments:
        - name: Non_Production
          prior: Library
        - name: Production
          prior: Non_Production
      content_views:
        - name: cv-kickstart-rhel8.4
          repos:
            - repo: Red Hat Enterprise Linux 8 for x86_64 - AppStream (Kickstart)
              product: Red Hat Enterprise Linux for x86_64
              releasever: 8.4
            - repo: Red Hat Enterprise Linux 8 for x86_64 - BaseOS (Kickstart)
              product: Red Hat Enterprise Linux for x86_64
              releasever: 8.4
        - name: cv-ansible-rhel8
          repos:
            - repo: Red Hat Ansible Engine 2 for RHEL 8 x86_64 (RPMs)
              product: Red Hat Ansible Engine            
        - name: cv-automationhub4.2-rhel8
          repos:
            - repo: Red Hat Automation Hub 4.2 for RHEL 8 x86_64 (RPMs)
              product: Red Hat Ansible Automation Platform
        - name: cv-e4s-server-rhel8.1
          repos:
            - repo: Red Hat Enterprise Linux 8 for x86_64 - BaseOS - Update Services for SAP Solutions (RPMs)
              product: Red Hat Enterprise Linux Server - Update Services for SAP Solutions
              releasever: 8.1
        - name: cv-e4s-appstream-rhel8.1
          repos:
            - repo: Red Hat Enterprise Linux 8 for x86_64 - AppStream - Update Services for SAP Solutions (RPMs)
              product: Red Hat Enterprise Linux Server - Update Services for SAP Solutions
              releasever: 8.1
        - name: cv-r4s-netweaver-rhel8.1
          repos:
            - repo: Red Hat Enterprise Linux 8 for x86_64 - SAP NetWeaver - Update Services for SAP Solutions (RPMs)
              product: RHEL for SAP - Update Services for SAP Solutions
              releasever: 8.1
        - name: cv-r4h-hana-rhel8.1
          repos:
            - repo: Red Hat Enterprise Linux 8 for x86_64 - SAP Solutions - Update Services for SAP Solutions (RPMs)
              product: RHEL for SAP HANA - Update Services for SAP Solutions
              releasever: 8.1
        - name: cv-e4s-satellitetools6.9-rhel8.1
          repos:
            - repo: Red Hat Satellite Tools 6.9 for RHEL 8 x86_64 - Update Services SAP Solutions (RPMs)
              product: Red Hat Enterprise Linux Server - Update Services for SAP Solutions
              releasever: 8.1
        - name: cv-e4s-highavailability-rhel8.1
          repos:
            - repo: Red Hat Enterprise Linux 8 for x86_64 - High Availability - Update Services for SAP Solutions (RPMs)
              product: Red Hat Enterprise Linux High Availability - Update Services for SAP Solutions
              releasever: 8.1
        - name: cv-e4s-server-rhel8.2
          repos:
            - repo: Red Hat Enterprise Linux 8 for x86_64 - BaseOS - Update Services for SAP Solutions (RPMs)
              product: Red Hat Enterprise Linux Server - Update Services for SAP Solutions
              releasever: 8.2
        - name: cv-e4s-appstream-rhel8.2
          repos:
            - repo: Red Hat Enterprise Linux 8 for x86_64 - AppStream - Update Services for SAP Solutions (RPMs)
              product: Red Hat Enterprise Linux Server - Update Services for SAP Solutions
              releasever: 8.2
        - name: cv-r4s-netweaver-rhel8.2
          repos:
            - repo: Red Hat Enterprise Linux 8 for x86_64 - SAP NetWeaver - Update Services for SAP Solutions (RPMs)
              product: RHEL for SAP - Update Services for SAP Solutions
              releasever: 8.2
        - name: cv-r4h-hana-rhel8.2
          repos:
            - repo: Red Hat Enterprise Linux 8 for x86_64 - SAP Solutions - Update Services for SAP Solutions (RPMs)
              product: RHEL for SAP HANA - Update Services for SAP Solutions
              releasever: 8.2
        - name: cv-e4s-satellitetools6.9-rhel8.2
          repos:
            - repo: Red Hat Satellite Tools 6.9 for RHEL 8 x86_64 - Update Services SAP Solutions (RPMs)
              product: Red Hat Enterprise Linux Server - Update Services for SAP Solutions
              releasever: 8.2
        - name: cv-e4s-highavailability-rhel8.2
          repos:
            - repo: Red Hat Enterprise Linux 8 for x86_64 - High Availability - Update Services for SAP Solutions (RPMs)
              product: Red Hat Enterprise Linux High Availability - Update Services for SAP Solutions
              releasever: 8.2
        - name: cv-server-rhel8
          repos:
            - repo: Red Hat Enterprise Linux 8 for x86_64 - BaseOS (RPMs)
              product: Red Hat Enterprise Linux for x86_64
              releasever: 8
        - name: cv-appstream-rhel8
          repos:
            - repo: Red Hat Enterprise Linux 8 for x86_64 - AppStream (RPMs)
              product: Red Hat Enterprise Linux for x86_64
              releasever: 8
        - name: cv-satellitetools6.9-rhel8
          repos:
            - repo: Red Hat Satellite Tools 6.9 for RHEL 8 x86_64 (RPMs)
              product: Red Hat Enterprise Linux for x86_64
        - name: cv-kickstart-rhel8.1
          repos:
            - repo: Red Hat Enterprise Linux 8 for x86_64 - AppStream (Kickstart)
              product: Red Hat Enterprise Linux for x86_64
              releasever: 8.1
            - repo: Red Hat Enterprise Linux 8 for x86_64 - BaseOS (Kickstart)
              product: Red Hat Enterprise Linux for x86_64
              releasever: 8.1      
      composite_content_views:
        - name: composite-rhel8
          auto_publish: false
          component_content_views:
            - name: cv-ansible-rhel8
            - name: cv-e4s-server-rhel8.2
            - name: cv-e4s-appstream-rhel8.2
            - name: cv-r4s-netweaver-rhel8.2
            - name: cv-r4h-hana-rhel8.2
            - name: cv-e4s-satellitetools6.9-rhel8.2
            - name: cv-e4s-highavailability-rhel8.2
            - name: cv-e4s-server-rhel8.1
            - name: cv-e4s-appstream-rhel8.1
            - name: cv-r4s-netweaver-rhel8.1
            - name: cv-r4h-hana-rhel8.1
            - name: cv-e4s-satellitetools6.9-rhel8.1
            - name: cv-e4s-highavailability-rhel8.1
            - name: cv-server-rhel8
            - name: cv-appstream-rhel8
            - name: cv-satellitetools6.9-rhel8
            - name: cv-kickstart-rhel8.1
            - name: cv-automationhub4.2-rhel8
            - name: cv-kickstart-rhel8.4
      activation_keys:
        - name: ak-sap-rhel8.1-production
          lifecycle_environment: Production
          content_view: composite-rhel8
          release_version: 8.1
          content_overrides:
            - label: rhel-8-for-x86_64-baseos-e4s-rpms
            - label: rhel-8-for-x86_64-appstream-e4s-rpms
            - label: satellite-tools-6.9-for-rhel-8-x86_64-e4s-rpms
            - label: rhel-8-for-x86_64-sap-netweaver-e4s-rpms
            - label: rhel-8-for-x86_64-sap-solutions-e4s-rpms
            - label: rhel-8-for-x86_64-highavailability-e4s-rpms
        - name: ak-sap-rhel8.1-non_production
          lifecycle_environment: Non_Production
          content_view: composite-rhel8
          release_version: 8.1
          content_overrides:
            - label: rhel-8-for-x86_64-baseos-e4s-rpms
            - label: rhel-8-for-x86_64-appstream-e4s-rpms
            - label: satellite-tools-6.9-for-rhel-8-x86_64-e4s-rpms
            - label: rhel-8-for-x86_64-sap-netweaver-e4s-rpms
            - label: rhel-8-for-x86_64-sap-solutions-e4s-rpms
            - label: rhel-8-for-x86_64-highavailability-e4s-rpms
        - name: ak-ansible-rhel8-production
          lifecycle_environment: Production
          content_view: composite-rhel8
          release_version: 8
          content_overrides:
            - label: rhel-8-for-x86_64-baseos-rpms
            - label: rhel-8-for-x86_64-appstream-rpms
            - label: satellite-tools-6.9-for-rhel-8-x86_64-e4s-rpms