---

- name: configure controller
  hosts:
    - all
  gather_facts: no
  pre_tasks:
    - name: include {{ demo }} controller configuration
      ansible.builtin.include_vars:
        file: "vars/{{ demo }}/controller-configuration.yml"
  tasks:
    - name: ansible controller configuration block
      block:
        - name: include pre-inventory sync configuration roles
          ansible.builtin.include_role:
            name: "{{ role }}"
          loop_control:
            loop_var: role
          loop:
            - redhat_cop.controller_configuration.organizations
            - redhat_cop.controller_configuration.credentials
            - redhat_cop.controller_configuration.execution_environments
            - redhat_cop.controller_configuration.teams
            - redhat_cop.controller_configuration.users
            - redhat_cop.controller_configuration.inventories
            - redhat_cop.controller_configuration.inventory_sources
            - redhat_cop.controller_configuration.inventory_source_update
        - name: pause for inventory sync
          ansible.builtin.pause:
            seconds: 30
        - name: include post-inventory sync configuration roles
          ansible.builtin.include_role:
            name: "{{ role }}"
          loop_control:
            loop_var: role
          loop:      
            - redhat_cop.controller_configuration.groups
            - redhat_cop.controller_configuration.projects
            - redhat_cop.controller_configuration.job_templates
            - redhat_cop.controller_configuration.workflow_job_templates
            - redhat_cop.controller_configuration.roles
      when:
        - configure_controller | bool