---

- name: create compliance hostgroups
  hosts:
    - all
  gather_facts: no
  tasks:
    - name: create compliance hostgroups in satellite
      redhat.satellite.hostgroup:
        username: admin
        password: "{{ satellite_password }}"
        validate_certs: false
        server_url: "https://{{ satellite_hostname }}"
        name: "{{ child_hostgroup }}"
        parent: "{{ parent_hostgroup }}"
        ansible_roles: "{{ ansible_roles }}"
        openscap_proxy: "{{ satellite_hostname }}"
      delegate_to: localhost
      throttle: 1
