---

- name: create compliance hostgroups
  hosts:
    - all
  gather_facts: no
  tasks:
    - name: create compliance hostgroups in satellite
      redhat.satellite.hostgroup:
        username: "{{ satellite.admin_username }}"
        password: "{{ satellite.admin_password }}"
        validate_certs: false
        server_url: "https://{{ inventory_hostname }}"
        name: "{{ hostgroup.name }}"
        parent: "{{ hostgroup.parent }}"
        ansible_roles: "{{ hostgroup.ansible_roles }}"
      loop_control:
        loop_var: hostgroup
      loop: "{{ hostgroups }}"
