---

- name: create compliance policies on console.redhat.com
  hosts:
    - all
  pre_tasks:
    - name: set parent_profile_id for OS | RHEL7
      ansible.builtin.set_fact:
        parent_profile_id: "{{ rhel7_parent_profile_id }}"
      when:
        - ansible_distribution_major_version == '7'
    - name: set parent_profile_id for OS | RHEL8
      ansible.builtin.set_fact:
        parent_profile_id: "{{ rhel8_parent_profile_id }}"
      when:
        - ansible_distribution_major_version == '8'
  tasks:
    - name: create compliance profile
      ansible.builtin.uri:
        url: https://console.redhat.com/api/compliance/v1/profiles
        user: "{{ crhc_username }}"
        password: "{{ crhc_password }}"
        method: POST
        force_basic_auth: yes
        body_format: json
        status_code:
          - 201
          - 406
        body:
          data:
            attributes:
              name: "{{ policy_name }}"
              parent_profile_id: "{{ parent_profile_id }}"
              compliance_threshold: 100
      register: create_compliance_policy
      changed_when:
        - create_compliance_policy.status == 201
      failed_when:
        - create_compliance_policy.status != 201
        - create_compliance_policy.status != 406
      delegate_to: localhost