---

- name: create compliance hostgroups
  hosts:
    - all
  gather_facts: no
  tasks:
    - name: create compliance hostgroups in satellite
      redhat.satellite.hostgroup:
        username: admin
        password: "{{ satellite_password }}"
        validate_certs: false
        server_url: "{{ satellite_url }}"
        name: "{{ child_hostgroup }}"
        parent: "{{ parent_hostgroup }}"
        ansible_roles: "{{ ansible_roles }}"
        openscap_proxy: "{{ satellite_url | regex_replace('https://', '') }}"
      delegate_to: localhost
      throttle: 1
