---

- name: create compliance hostgroups
  hosts:
    - all
  tasks:
    - name: create compliance hostgroups in satellite
      redhat.satellite.hostgroup:
        username: admin
        password: "{{ satellite_password }}"
        validate_certs: false
        server_url: "https://{{ satellite_hostname }}"
        name: "{{ policy_shortname }}"
        parent: "rhel{{ ansible_distribution_major_version }}"
        ansible_roles: "{{ ansible_roles }}"
        openscap_proxy: "{{ satellite_hostname }}"
      delegate_to: localhost
      throttle: 1
