---

- name: create compliance policies on console.redhat.com
  hosts:
    - all
  module_defaults:
    ansible.builtin.uri:
        user: "{{ crhc_username }}"
        password: "{{ crhc_password }}"
        force_basic_auth: yes
  pre_tasks:
    - name: gather information for policy creation
      block:
        - name: grab latest ssg_version
          ansible.builtin.uri:
            url: https://console.redhat.com/api/compliance/v1/benchmarks?search=latest_supported_os_minor_version={{ ansible_distribution_version.split('.')[-1] }}+os_major_version={{ ansible_distribution_major_version }}&limit=1
          register: ssg_version_query
        - name: set ssg_version
          ansible.builtin.set_fact:
            ssg_version: "{{ ssg_version_query.json.data[0].attributes.version }}"
        - name: grab canonical profile
          ansible.builtin.uri:
            url:  https://console.redhat.com/api/compliance/v1/profiles?search=canonical=true+ssg_version={{ ssg_version }}+os_major_version={{ ansible_distribution_major_version }}+ref_id~{{ child_hostgroup }}
          register: canonical_profile_query
        - name: set canonical_profile_id
          ansible.builtin.set_fact:
            canonical_profile_id: "{{ canonical_profile_query.json.data[0].id }}"
      delegate_to: localhost
      throttle: 1           
  tasks:
    - name: create compliance profile
      ansible.builtin.uri:
        url: https://console.redhat.com/api/compliance/v1/profiles
        method: POST
        body_format: json
        status_code:
          - 201
          - 406
        body:
          data:
            attributes:
              parent_profile_id: "{{ canonical_profile_id }}"
              compliance_threshold: 95
      register: create_compliance_policy
      changed_when:
        - create_compliance_policy.status == 201
      failed_when:
        - create_compliance_policy.status != 201
        - create_compliance_policy.status != 406
      delegate_to: localhost
      throttle: 1