---

- name: create compliance policies on console.redhat.com
  hosts:
    - all
  gather_facts: no
  tasks:
    - name: create compliance profile
      ansible.builtin.uri:
        url: https://console.redhat.com/api/compliance/v1/profiles
        user: "{{ crhc_username }}"
        password: "{{ crhc_password }}"
        method: POST
        force_basic_auth: yes
        body_format: json
        status_code:
          - 201
          - 406
        body:
          data:
            attributes:
              name: "{{ policy_name }}"
              parent_profile_id: "{{ parent_profile_id }}"
              compliance_threshold: 95
      register: create_compliance_policy
      changed_when:
        - create_compliance_policy.status == 201
      failed_when:
        - create_compliance_policy.status != 201
        - create_compliance_policy.status != 406
      delegate_to: localhost
      throttle: 1