---

- name: deploy compliance scanning via satellite
  hosts:
    - all
  tasks:
    - name: run ansible roles against hosts via satellite
      redhat.satellite.job_invocation:
        username: admin
        password: "{{ satellite_password }}"
        validate_certs: false
        server_url: "https://{{ satellite_hostname }}"
        job_template: Ansible Roles - Ansible Default
        search_query: "hostgroup_fullname = {{ ansible_distribution_major_version }}/{{ policy_shortname }}"
      delegate_to: localhost