---

- name: move hosts to appropriate hostgroups
  hosts:
    - all
  gather_facts: no
  tasks:
    - name: move host to appropriate compliance hostgroup and set scap proxy
      redhat.satellite.host:
        username: "{{ satellite.admin_username }}"
        password: "{{ satellite.admin_password }}"
        validate_certs: false
        server_url: "{{ satellite_url }}"
        name: "{{ inventory_hostname }}"
        hostgroup: "{{ parent_hostgroup }}/{{ child_hostgroup }}"
      delegate_to: localhost
      throttle: 1