---

- name: move hosts to appropriate hostgroups
  hosts:
    - all
  tasks:
    - name: move host to appropriate compliance hostgroup
      redhat.satellite.host:
        username: admin
        password: "{{ satellite_password }}"
        validate_certs: false
        server_url: "https://{{ satellite_hostname }}"
        name: "{{ inventory_hostname }}"
        hostgroup: "rhel{{ ansible_distribution_major_version }}/{{ policy_shortname }}"
      delegate_to: localhost
      throttle: 1