---

- name: run compliance role based on desired baseline
  hosts:
    - all
  tasks:
    - name: include compliance role
      ansible.builtin.include_role:
        name: "redhatofficial.rhel{{ ansible_distribution_major_version }}_{{ policy_shortname }}"