---

- name: import and upload scap content and related to satellite
  hosts:
    - all
  module_defaults:
    ansible.builtin.uri:
      user: admin
      password: "{{ satellite_password }}"
      force_basic_auth: yes
      validate_certs: no
  tasks:
    - name: make API calls to import role and variables
      block:
        - name: import theforeman.foreman_scap_client ansible role
          ansible.builtin.uri:
            url: https://{{ inventory_hostname }}/ansible/api/ansible_roles/import
            method: PUT
            body:
              location_id: '1'
              organization_id: '1'
              proxy_id: '1'
              role_names:
                - theforeman.foreman_scap_client
        - name: import ansible vars from theforeman.foreman_scap_client ansible role
          ansible.builtin.uri:
            url: https://{{ inventory_hostname }}/ansible/api/ansible_variables/import
            validate_certs: no
            body:
              location_id: '1'
              organization_id: '1'
              proxy_id: '1'
      delegate_to: localhost
    - name: upload scap content to satellite
      ansible.builtin.shell:
        cmd: foreman-rake foreman_openscap:bulk_upload:default