---

controller_organizations:
  - name: "{{ audience }}"
    galaxy_credentials:
      - MSP Lab Automation Hub - RH Certified
      - MSP Lab Automation Hub - Community
      - Ansible Galaxy

controller_credentials:
  - name: S4HANA Deployment Peripheral Credentials
    credential_type: Demo Provisioner Peripheral Credentials
    organization: "{{ audience }}"
  - name: S4HANA Deployment Credentials
    credential_type: Machine
    organization: "{{ audience }}"
    inputs:
      username: root
      password: "{{ ansible_password }}"

controller_execution_environments:
  - name: S4HANA Deployment Demo EE
    image: 'aap20-hub.josh.lab.msp.redhat.com/s4hana-deployment-demo-ee:latest'
    organization: "{{ audience }}"
    credential: MSP Lab AAP20 Automation Hub

controller_teams:
  - name: "{{ audience }} SAP Infrastructure Team"
    description: infrastructure team
    organization: "{{ audience }}"
  - name: "{{ audience }} BASIS Team"
    description: BASIS team
    organization: "{{ audience }}"
  - name: "{{ audience }} Business Analyst Team"
    description: BASIS team
    organization: "{{ audience }}"

controller_user_accounts:
  - username: "{{ audience }}_infrastructure"
    password: "{{ ansible_password }}"
    email: dont@email.me
    update_secrets: no
  - username: "{{ audience }}_basis"
    password: "{{ ansible_password }}"
    email: dont@email.me
    update_secrets: no
  - username: "{{ audience }}_business_analyst"
    password: "{{ ansible_password }}"
    email: dont@email.me
    update_secrets: no

controller_inventories:
  - name: "{{ audience }} SAP Infrastructure"
    organization: "{{ audience }}"
    variables:
      company: "{{ audience }}"

controller_groups:
  - name: primary
    inventory: "{{ audience }} SAP Infrastructure"
    variables:
      sap_hana_hsr_role: primary
  - name: secondary
    inventory: "{{ audience }} SAP Infrastructure"
    variables:
      sap_hana_hsr_role: secondary
  - name: hana
    inventory: "{{ audience }} SAP Infrastructure"
    children:
      - primary
      - secondary
  - name: netweaver
    inventory: "{{ audience }} SAP Infrastructure"
  - name: s4hana
    inventory: "{{ audience }} SAP Infrastructure"
    children:
      - hana
      - netweaver
    variables:
      os: rhel8.4
      application: sap
  - name: production
    inventory: "{{ audience }} SAP Infrastructure"
    variables:
      lifecycle_environment: production

controller_projects:
  - name: "{{ audience }} S4HANA Deployment Code"
    organization: "{{ audience }}"
    scm_branch: main
    scm_type: git
    scm_url: https://github.com/jjaswanson4/patching-demo.git
    wait: yes

controller_templates:
  - name: Add Hosts to Controller Inventory
    inventory: Local Action Inventory
    project: "{{ audience }} S4HANA Deployment Code"
    playbook: demos/s4hana-deployment/add-hosts-to-controller.yml
    execution_environment: S4HANA Deployment Demo EE
    credentials:
      - S4HANA Deployment Peripheral Credentials

controller_templates: >
  {{ controller_templates }} +
  {{ lookup('file', '../demos/common/vars/provisioner-configuration.yml') | from_yaml | json_query('controller_templates[?name == `Provision Demo Hosts`]') }} +
  {{ lookup('file', '../demos/common/vars/provisioner-configuration.yml') | from_yaml | json_query('controller_templates[?name == `Preconfigure for SAP`]') }} +
  {{ lookup('file', '../demos/common/vars/provisioner-configuration.yml') | from_yaml | json_query('controller_templates[?name == `Preconfigure for HANA`]') }} +
  {{ lookup('file', '../demos/common/vars/provisioner-configuration.yml') | from_yaml | json_query('controller_templates[?name == `Preconfigure for Netweaver`]') }} +
  {{ lookup('file', '../demos/common/vars/provisioner-configuration.yml') | from_yaml | json_query('controller_templates[?name == `Deploy SAP HANA`]') }} +
  {{ lookup('file', '../demos/common/vars/provisioner-configuration.yml') | from_yaml | json_query('controller_templates[?name == `Install Netweaver`]') }} +
  {{ lookup('file', '../demos/common/vars/provisioner-configuration.yml') | from_yaml | json_query('controller_templates[?name == `Reinstate HSR`]') }}

controller_workflows:
  - name: Provision S4HANA SID
    organization: "{{ audience }}"
    state: "{{ controller_state | default('present') }}"
    survey_enabled: yes
    survey:
      name: ''
      description: ''
      spec:
        - type: text
          question_name: "What is the desired SAP System Identification (SID)?"
          variable: sid
          required: yes
          default: DS4
        - type: text
          question_name: "What is the SAR file name?"
          variable: sap_hana_deployment_bundle_sar_file_name
          required: yes
          default: IMDB_SERVER20_046_0-80002031.SAR
        - type: text
          question_name: "What is the name of the SAPCAR file?"
          variable: sap_hana_deployment_sapcar_file_name
          required: yes
          default: SAPCAR_1010-70006178.EXE
        - type: text
          question_name: "What is the HANA env type?"
          variable: sap_hana_deployment_hana_env_type
          required: yes
          default: development
        - type: text
          question_name: "What is the HANA instance number?"
          variable: sap_hana_deployment_hana_instance_number
          required: yes
          default: "00"
        - type: text
          question_name: "What is the desired S4HANA product?"
          variable: "{{ sap_s4hana_deployment_product_id }}"
          default: "NW_ABAP_OneHost:S4HANA1909.CORE.HDB.ABAP"
        - type: text
          question_name: "What is the S4HANA SAPCAR file name?"
          variable: sap_s4hana_deployment_sapcar_file_name
          default: SAPCAR_1010-70006178.EXE
        - type: text
          question_name: "What is the S4HANA swpm file name?"
          variable: sap_s4hana_deployment_swpm_sar_file_name
          default: SWPM20SP04_6-80003424.SAR
        - type: text
          question_name: "How many deployment parallel jobs should run?"
          variable: sap_s4hana_deployment_parallel_jobs_nr
          default: "30"
        - type: text
          question_name: "What is the S4HANA deployment igs file name?"
          variable: sap_s4hana_deployment_parallel_jobs_nr
          default: igsexe_9-80003187.sar
        - type: text
          question_name: "What is the S4HANA deployment igs helper file name?"
          variable: sap_s4hana_deployment_igs_helper_file_name
          default: igshelper_17-10010245.sar
        - text: text
          question_name: "What is the S4HANA deployment kernel dependent file name?"
          variable: sap_s4hana_deployment_kernel_dependent_file_name
          default: SAPEXEDB_201-80003385.SAR
        - text: text
          question_name: "What is the S4HANA deployment kernel independent file name?"
          variable: sap_s4hana_deployment_kernel_independent_file_name
          default: SAPEXE_201-80003386.SAR

    simplified_workflow_nodes:
      - unified_job_template: Provision Systems
        identifier: node102
        inventory: Patching Demo Infrastructure
        limit: sap
        success_nodes:
          - node103
          - node104
        failure_nodes:
          - node202
      - unified_job_template: Configure Ansible Controller
        identifier: node103
        limit: patching-demo
        success_nodes:
          - node112
        failure_nodes:
          - node203
      - unified_job_template: Preconfigure for SAP
        identifier: node104
        inventory: Patching Demo Infrastructure
        limit: sap
        success_nodes:
          - node105
          - node106
        failure_nodes:
          - node204
      - unified_job_template: Preconfigure for HANA
        identifier: node105
        inventory: Patching Demo Infrastructure
        limit: hana
        success_nodes:
          - node107
          - node108
          - node112
        failure_nodes:
          - node205
      - unified_job_template: Preconfigure for Netweaver
        identifier: node106
        inventory: Patching Demo Infrastructure
        limit: netweaver
        success_nodes:
          - node109
          - node110
          - node112
        failure_nodes:
          - node206
      - unified_job_template: Deploy SAP HANA
        identifier: node107
        inventory: Patching Demo Infrastructure
        limit: 'hana:&non_production'
        success_nodes:
          - node109
        failure_nodes:
          - node207
      - unified_job_template: Deploy SAP HANA
        identifier: node108
        inventory: Patching Demo Infrastructure
        limit: 'hana:&production'
        success_nodes:
          - node110
        failure_nodes:
          - node208
      - unified_job_template: Install Netweaver
        identifier: node109
        inventory: Patching Demo Infrastructure
        limit: 'netweaver:&non_production'
        all_parents_must_converge: yes
        success_nodes:
          - node111
        failure_nodes:
          - node209
      - unified_job_template: Install Netweaver
        identifier: node110
        inventory: Patching Demo Infrastructure
        limit: 'netweaver:&production'
        all_parents_must_converge: yes
        success_nodes:
          - node111
        failure_nodes:
          - node210
      - unified_job_template: Reinstate HSR
        identifier: node111
        inventory: Patching Demo Infrastructure
        limit: 'hana:&primary'
        all_parents_must_converge: yes
        success_nodes:
          - node999
        failure_nodes:
          - node211

controller_roles:

