---

# By default, the org 'Demo Provisioner' is created and resources are configured there,
# Use this variable to override this behavior.
# For example, overriding to 'Default' will put the resources into the default controller organization.
controller_organization: Demo Provisioner

# This is the default project name. It is a var so demos can import specific job templates and override the project locally.
# Change this to change the name of the project for the provisioner job templates.
project: Demo Provisioner Codebase

# This is the default prefix for assets created for this demo.
# Change this variable to use a different prefix.
demo_prefix: "S4HANA Deployment Demo"

#
#
inventory: "{{ demo_prefix }} Infrastructure"

#
#
execution_environment:
  name: Demo Provisioner EE
  image: patching-demo-provisioner-ee

#
#
test: patching-controller.josh.lab.msp.redhat.com
controller:
  hostname: patching-controller.josh.lab.msp.redhat.com
  configuration_file: demos/patching/vars/controller-configuration.yml
  ip_address: 10.15.121.13

#
#
test2: patching-satellite.josh.lab.msp.redhat.com
satellite:
  hostname: patching-satellite.josh.lab.msp.redhat.com
  configuration_file: demos/patching/vars/satellite-configuration.yml
  ip_address: 10.15.121.3

# Provisioner components

controller_organizations: []
controller_credential_types: []
controller_credentials: []
controller_execution_environments: []
controller_inventories: []
controller_projects: []
controller_hosts: []
controller_groups: []
controller_templates: []

controller_workflows:
  - name: Provision S4HANA Deployment Demo
    organization: Demo Provisioner
    state: "{{ controller_state | default('present') }}"
    extra_vars:
      demo: s4hana-deployment
    survey_enabled: yes
    survey: "{{ lookup('file', '../resources/controller/provisioner-workflow-survey.yml') | from_yaml }}"
    simplified_workflow_nodes:
    # Work nodes
      - unified_job_template: Setup Red Hat Satellite
        identifier: node101
        inventory: "{{ inventory }}"
        success_nodes:
          - node102
      - unified_job_template: Setup Ansible Controller
        identifier: node102
        inventory: "{{ inventory }}"