---

controller_inventories:
  - name: S4HANA Deployment Demo Infrastructure
    organization: Demo Provisioner

controller_hosts:
  - name: sap-deployment-satellite.josh.lab.msp.redhat.com
    inventory: S4HANA Deployment Demo Infrastructure
    variables: "{{ lookup('file', 'demos/s4hana-deployment/vars/satellite-configuration.yml') | from_yaml }}"
  - name: s4hana-deployment-demo
    inventory: Local Action Inventory
    variables: "{{ lookup('file', 'demos/s4hana-deployment/vars/controller-configuration.yml') | from_yaml }}"
    
controller_groups:
  - name: satellite
    inventory: S4HANA Deployment Demo Infrastructure
    hosts:
      - sap-deployment-satellite.josh.lab.msp.redhat.com
  - name: management_plane
    inventory: S4HANA Deployment Demo Infrastructure
    variables:
      lifecycle_environment: production
      provisioning:
        satellite:
          server: satellite06.lab.msp.redhat.com
          username: admin
          password: "{  { satellite_password }}"
        host_group: "{  { os }}"
        organization: MSP Lab
        location: MSP Lab
        method: bootdisk
        dns_domain: josh.lab.msp.redhat.com
        cpus: "{  { cpus }}"
        memory_mb: "{  { memory_mb }}"
        activation_keys: "ak-{  { application }}-{  { os }}-{  { lifecycle_environment }}"
    children:
      - satellite

controller_templates:
  - name: Setup Red Hat Satellite
    organization: Demo Provisioner
    inventory: S4HANA Deployment Demo Infrastructure
    limit: satellite
    project: Demo Provisioner Codebase
    playbook: provisioner/playbooks/deploy-satellite.yml
    execution_environment: Demo Provisioner EE
    extra_vars:
      run_additional_roles: no
    credentials:
      - Demo Provisioner Peripheral Credentials
      - S4HANA Deployment Demo Root Account
  - name: Teardown Red Hat Satellite
    organization: Demo Provisioner
    inventory: S4HANA Deployment Demo Infrastructure
    limit: satellite
    project: Demo Provisioner Codebase
    playbook: provisioner/playbooks/teardown-systems.yml
    execution_environment: Demo Provisioner EE
    credentials:
      - Demo Provisioner Peripheral Credentials
  - name: Cleanup Satellite DNS Records
    organization: Demo Provisioner
    inventory: S4HANA Deployment Demo Infrastructure
    limit: satellite
    project: Demo Provisioner Codebase
    playbook: provisioner/playbooks/delete-dns-records.yml
    execution_environment: Demo Provisioner EE
    credentials:
      - Demo Provisioner Peripheral Credentials

controller_workflows:
  - name: Provision S4HANA Deployment Demo
    organization: Demo Provisioner
    state: "{{ controller_state | default('present') }}"
    extra_vars:
      demo: s4hana-deployment
    survey_enabled: yes
    survey:
      name: ''
      description: ''
      spec:
        - type: text
          question_name: "Demo Audience?"
          question_description: "Who is the audience for this demo?"
          variable: audience
          required: yes
        - type: text
          question_name: "Provisioner?"
          question_description: "Who is provisioning this demo?"
          variable: provisioner
          required: yes
          default: 'Josh Swanson'
        - type: text
          question_name: "Provisioner's Email?"
          question_description: "What is the provisioner's email address?"
          variable: provisioner_email
          required: yes
          default: 'joshswanson@redhat.com'
        - type: multiplechoice
          question_name: Deploy Satellite?
          question_description: Should satellite be deployed?
          variable: deploy_satellite
          choices:
            - "yes"
            - "no"
          default: "yes"
          required: yes
        - type: multiplechoice
          question_name: Configure controller?
          question_description: Should controller be configured?
          variable: configure_controller
          choices:
            - "yes"
            - "no"
          default: "yes"
          required: yes          
    simplified_workflow_nodes:
    # Work nodes
      - unified_job_template: Configure Ansible Controller
        identifier: node101
        limit: s4hana-deployment-demo
        success_nodes:
          - node999
        failure_nodes:
          - node201
      - unified_job_template: Setup Red Hat Satellite
        identifier: node102
        success_nodes:
          - node999
        failure_nodes:
          - node202
    # Notification Nodes
      - unified_job_template: Send Provisioner Email | Succeeded
        identifier: node999
        all_parents_must_converge: yes
      - unified_job_template: Send Provisioner Email | Failed
        identifier: node201
      - unified_job_template: Send Provisioner Email | Failed
        identifier: node202
  # - name: Teardown Patching Demo
  #   organization: Demo Provisioner
  #   state: "{{ controller_state | default('present') }}"
  #   extra_vars:
  #     demo: patching
  #   survey_enabled: yes
  #   survey:
  #     name: ''
  #     description: ''
  #     spec:
  #       - type: text
  #         question_name: "Demo Audience?"
  #         question_description: "Who is the audience for this demo"
  #         variable: audience
  #         required: yes
  #   simplified_workflow_nodes:
  #     - unified_job_template: Remove Controller Configuration
  #       identifier: node101
  #     - unified_job_template: Teardown Red Hat Satellite
  #       identifier: node102
  #     - unified_job_template: Cleanup Satellite DNS Records
  #       identifier: node103
