---

application: sap

nfs_shares:
  - src: 10.15.108.14:/mnt/data01/sap
    path: /software

sap_preconfigure_modify_etc_hosts: true
sap_domain: "josh.lab.msp.redhat.com"
sap_hostagent_installation_type: "rpm"
sap_hostagent_rpm_remote_path: "/software/SAPHOSTAGENT"
sap_hostagent_rpm_file_name: "saphostagentrpm_44-20009394.rpm"
sap_preconfigure_fail_if_reboot_required: no
sap_preconfigure_selinux_state: permissive