---

ansible_host: "{{ controller.ip_address }}"
ip_address: "{  { ansible_host }}"
cpus: 4
memory_mb: 16384
os: rhel8
application: general

htop_url: https://dl.fedoraproject.org/pub/epel/8/Everything/x86_64/Packages/h/htop-3.0.5-1.el8.x86_64.rpm

aap_download_url: http://satellite06.lab.msp.redhat.com/pub/ansible-automation-platform-setup-bundle-2.0.0-1-early-access.tar.gz
aap_bundle: ansible-automation-platform-setup-bundle-2.0.0-1-early-access.tar.gz

controller_install:
  admin_password: "{  { controller_password }}"
  pg:
    password: 'R3dh4t123'

bootstrap_controller: yes

controller_configuration_credentials_secure_logging: no

controller_license:
  manifest: /tmp/controller-manifest.zip

controller_organizations:
  - name: "{  { audience }}"

controller_credentials:
  - name: RHEL Root Credentials
    credential_type: Machine
    organization: "{  { audience }}"
    inputs:
      username: root
      password: "{{ ansible_password }}"
  - name: Active Directory Domain Administrator Credentials
    organization: "{  { audience }}"
    credential_type: Machine
    inputs:
      username: Administrator@ad.josh.lab.msp.redhat.com
      password: "{{ ansible_password }}"
  - name: MSP Lab AAP20 Automation Hub
    organization: "{  { audience }}"
    credential_type: Container Registry
    inputs:
      host: aap20-hub.josh.lab.msp.redhat.com
      username: admin
      password: "{{ ansible_password }}"
      verify_ssl: no

controller_execution_environments:
  - name: IDM-AD Integration Demo EE
    image: 'aap20-hub.josh.lab.msp.redhat.com/idm-ad-integration-demo-ee:latest'
    organization: "{  { audience }}"
    credential: MSP Lab AAP20 Automation Hub

controller_inventories:
  - name: "{  { audience }} Infrastructure"
    organization: "{  { audience }}"

controller_hosts:
  - name: ad-dc1.ad.josh.lab.msp.redhat.com
    inventory: "{  { audience }} Infrastructure"
    variables:
      ansible_host: 10.15.121.60
  - name: ad-dc2.ad.josh.lab.msp.redhat.com
    inventory: "{  { audience }} Infrastructure"
    variables:
      ansible_host: 10.15.121.61
  - name: idm01.idm.josh.lab.msp.redhat.com
    inventory: "{  { audience }} Infrastructure"
    variables:
      ansible_host: 10.15.121.62
  - name: idm02.idm.josh.lab.msp.redhat.com
    inventory: "{  { audience }} Infrastructure"
    variables:
      ansible_host: 10.15.121.63
  - name: trust-client-1.idm.josh.lab.msp.redhat.com
    inventory: "{  { audience }} Infrastructure"
    variables:  
      ansible_host: 10.15.121.64
  - name: trust-client-2.idm.josh.lab.msp.redhat.com
    inventory: "{  { audience }} Infrastructure"
    variables:  
      ansible_host: 10.15.121.65
  - name: trust-client-3.idm.josh.lab.msp.redhat.com
    inventory: "{  { audience }} Infrastructure"
    variables:  
      ansible_host: 10.15.121.66
  - name: trust-client-4.idm.josh.lab.msp.redhat.com
    inventory: "{  { audience }} Infrastructure"
    variables:  
      ansible_host: 10.15.121.67
  - name: trust-client-5.idm.josh.lab.msp.redhat.com
    inventory: "{  { audience }} Infrastructure"
    variables:  
      ansible_host: 10.15.121.68

controller_groups:
  - name: pdc
    inventory: "{  { audience }} Infrastructure"
    hosts:
      - ad-dc1.ad.josh.lab.msp.redhat.com
  - name: domain_controllers
    inventory: "{  { audience }} Infrastructure"
    hosts:
      - ad-dc2.ad.josh.lab.msp.redhat.com
    variables:
      pdc_ip_address: "{  { hostvars['ad-dc1.ad.josh.lab.msp.redhat.com']['ansible_host'] }}"
  - name: active_directory
    inventory: "{  { audience }} Infrastructure"
    children:
      - pdc
      - domain_controllers
    variables:
  - name: windows
    inventory: "{  { audience }} Infrastructure"
    children:
      - active_directory
    variables:
      ansible_connection: winrm
      ansible_winrm_transport: ntlm
      ansible_winrm_server_cert_validation: ignore
      dns_zone: ad.josh.lab.msp.redhat.com
  - name: master
    inventory: "{  { audience }} Infrastructure"
    hosts:
      - idm01.idm.josh.lab.msp.redhat.com
    variables:
      ipaserver_setup_dns: yes
      ipaserver_allow_zone_overlap: yes
      ipaserver_setup_firewalld: no
      ipaserver_forwarders:
        - 10.11.5.19
        - 10.2.32.1
      ipaserver_setup_adtrust: yes
  - name: replicas
    inventory: "{  { audience }} Infrastructure"
    hosts:
      - idm02.idm.josh.lab.msp.redhat.com  
    variables:
      ipareplica_setup_dns: yes
      ipareplica_allow_zone_overlap: yes
      ipareplica_setup_firewalld: no
      ipareplica_forwarders:
        - 10.11.5.19
        - 10.2.32.1
      ipareplica_setup_adtrust: yes
      ipareplica_setup_ca: yes
      dns_resolv:
        search_domains:
          - idm.josh.lab.msp.redhat.com
          - josh.lab.msp.redhat.com
          - lab.msp.redhat.com
        nameservers:
          - "{  { hostvars['idm01.idm.josh.lab.msp.redhat.com']['ansible_host'] }}"
          - 10.15.108.5
        options:
          - 'timeout:1'
  - name: clients
    inventory: "{  { audience }} Infrastructure"
    hosts:
      - trust-client-1.idm.josh.lab.msp.redhat.com
      - trust-client-2.idm.josh.lab.msp.redhat.com
      - trust-client-3.idm.josh.lab.msp.redhat.com
      - trust-client-4.idm.josh.lab.msp.redhat.com
      - trust-client-5.idm.josh.lab.msp.redhat.com
    variables:
      cpus: 2
      memory_mb: 4096
      ipaclient_domain: idm.josh.lab.msp.redhat.com
      ipaclient_mkhomedir: yes
      dns_resolv:
        search_domains:
          - idm.josh.lab.msp.redhat.com
          - josh.lab.msp.redhat.com
          - lab.msp.redhat.com
        nameservers:
          - "{  { hostvars['idm01.idm.josh.lab.msp.redhat.com']['ansible_host'] }}"
          - "{  { hostvars['idm02.idm.josh.lab.msp.redhat.com']['ansible_host'] }}"
          - 10.15.120.4
        options:
          - 'timeout:1'
  - name: infra
    inventory: "{  { audience }} Infrastructure"
    children:
      - master
      - replicas
    variables:
      crypto_policies_policy: DEFAULT:AD-SUPPORT
      crypto_policies_reboot_ok: yes
  - name: idm
    inventory: "{  { audience }} Infrastructure"
    children:
      - infra
      - clients
    variables:
      ipaadmin_principal: admin
      ipaadmin_password: "{  { ansible_password }}"
      ipadm_password: "{  { ansible_password }}"
      ipaserver_domain: idm.josh.lab.msp.redhat.com
      ipaserver_realm: IDM.JOSH.LAB.MSP.REDHAT.COM
      reverse_zone_ip: 10.15.121.0/24
  - name: rhel
    inventory: "{  { audience }} Infrastructure"
    children:
      - idm

controller_projects:
  - name: "{  { audience }} Code"
    organization: "{  { audience }}"
    scm_branch: main
    scm_type: git
    scm_url: https://github.com/jjaswanson4/patching-demo.git
    wait: yes

controller_templates:
  - name: Setup for IDM Install
    inventory: "{  { audience }} Infrastructure"
    limit: infra
    project: "{  { audience }} Code"
    organization: "{  { audience }}"
    playbook: demos/idm-ad/playbooks/setup-for-idm.yml
    execution_environment: IDM-AD Integration Demo EE
    credentials:
      - RHEL Root Credentials
  - name: Install IDM Master
    inventory: "{  { audience }} Infrastructure"
    limit: master
    project: "{  { audience }} Code"
    organization: "{  { audience }}"
    playbook: demos/idm-ad/playbooks/install-idm-master.yml
    execution_environment: IDM-AD Integration Demo EE
    credentials:
      - RHEL Root Credentials
  - name: Install IDM Replicas
    inventory: "{  { audience }} Infrastructure"
    limit: replicas
    project: "{  { audience }} Code"
    organization: "{  { audience }}"
    playbook: demos/idm-ad/playbooks/install-idm-replica.yml
    execution_environment: IDM-AD Integration Demo EE
    credentials:
      - RHEL Root Credentials
  - name: Create Reverse Zone
    inventory: "{  { audience }} Infrastructure"
    limit: master
    project: "{  { audience }} Code"
    organization: "{  { audience }}"
    playbook: demos/idm-ad/playbooks/create-reverse-zone-in-idm.yml
    execution_environment: IDM-AD Integration Demo EE
    credentials:
      - RHEL Root Credentials  
  - name: Setup AD for Trust
    inventory: "{  { audience }} Infrastructure"
    limit: pdc
    project: "{  { audience }} Code"
    organization: "{  { audience }}"
    playbook: demos/idm-ad/playbooks/setup-ad-for-ad-trust.yml
    execution_environment: IDM-AD Integration Demo EE
    credentials:
      - Active Directory Domain Administrator Credentials
  - name: Setup IDM for Trust
    inventory: "{  { audience }} Infrastructure"
    limit: master
    project: "{  { audience }} Code"
    organization: "{  { audience }}"
    playbook: demos/idm-ad/playbooks/setup-idm-for-ad-trust.yml
    execution_environment: IDM-AD Integration Demo EE
    credentials:
      - RHEL Root Credentials
  - name: Create AD Trust
    inventory: "{  { audience }} Infrastructure"
    limit: master
    project: "{  { audience }} Code"
    organization: "{  { audience }}"
    playbook: demos/idm-ad/playbooks/create-ad-trust.yml
    execution_environment: IDM-AD Integration Demo EE
    credentials:
      - RHEL Root Credentials
  - name: Register Systems to IDM
    inventory: "{  { audience }} Infrastructure"
    limit: clients
    project: "{  { audience }} Code"
    organization: "{  { audience }}"
    playbook: demos/idm-ad/playbooks/register-system-to-idm.yml
    execution_environment: IDM-AD Integration Demo EE
    credentials:
      - RHEL Root Credentials

controller_workflows:
  - name: Integrate IDM with AD for Linux Authentication
    organization: "{  { audience }}"
    state: "{{ controller_state | default('present') }}"
    simplified_workflow_nodes:
      - approval_node:
          name: Approve 'Setup for IDM Install'
        identifier: node101
        success_nodes:
          - node102
      - unified_job_template: Setup for IDM Install 
        identifier: node102
        success_nodes:
          - node103
      - approval_node:
          name: Approve 'Install IDM Master'
        identifier: node103
        success_nodes:
          - node104
      - unified_job_template: Install IDM Master
        identifier: node104
        success_nodes:
          - node105
      - approval_node:
          name: Approve 'Install IDM Replicas'
        identifier: node105
        success_nodes:
          - node106
      - unified_job_template: Install IDM Replicas
        identifier: node106
        success_nodes:
          - node107
      - approval_node:
          name: Approve 'Create Reverse Zone'
        identifier: node107
        success_nodes:
          - node108
      - unified_job_template: Create Reverse Zone
        identifier: node108
        success_nodes:
          - node109
      - approval_node:
          name: Approve 'Setup AD for Trust'
        identifier: node109
        success_nodes:
          - node110
      - unified_job_template: Setup AD for Trust
        identifier: node110
        success_nodes:
          - node111
      - approval_node:
          name: Approve 'Setup IDM for Trust'
        identifier: node111
        success_nodes:
          - node112
      - unified_job_template: Setup IDM for Trust
        identifier: node112
        success_nodes:
          - node113
      - approval_node:
          name: Approve 'Create AD Trust'
        identifier: node113
        success_nodes:
          - node114
      - unified_job_template: Create AD Trust
        identifier: node114
        success_nodes:
          - node115
      - approval_node:
          name: Approve 'Register Systems to IDM'
        identifier: node115
        success_nodes:
          - node116
      - unified_job_template: Register Systems to IDM
        identifier: node116
