---

controller_hostname: aap20-controller.josh.lab.msp.redhat.com
controller_validate_certs: no
controller_username: admin

controller_organizations:
  - name: "{{ audience }}"
    galaxy_credentials:
      - MSP Lab Automation Hub - RH Certified
      - MSP Lab Automation Hub - Community
      - Ansible Galaxy

controller_credential_types:
  - name: S4HANA Deployment Peripheral Credentials
    organization: "{{ audience }}"
    kind: cloud
    injectors:
      extra_vars:
        dns_pass: "{{ dns_pass }}"
        ansible_password: "{{ ansible_password }}"
        satellite_password: "{{ satellite_password }}"
        vcenter_password: "{{ vcenter_password }}"
        controller_password: "{{ controller_password }}"

controller_credentials:
  - name: S4HANA Deployment Peripheral Credentials
    credential_type: S4HANA Deployment Peripheral Credentials
    organization: "{{ audience }}"
  - name: S4HANA Deployment Credentials
    credential_type: Machine
    organization: "{{ audience }}"
    inputs:
      username: root
      password: "{{ ansible_password }}"

controller_execution_environments:
  - name: S4HANA Deployment Demo EE
    image: 'aap20-hub.josh.lab.msp.redhat.com/s4hana-deployment-demo-ee:latest'
    organization: "{{ audience }}"
    credential: MSP Lab AAP20 Automation Hub

controller_teams:
  - name: "{{ audience }} SAP Infrastructure Team"
    description: infrastructure team
    organization: "{{ audience }}"
  - name: "{{ audience }} BASIS Team"
    description: BASIS team
    organization: "{{ audience }}"
  - name: "{{ audience }} Business Analyst Team"
    description: BASIS team
    organization: "{{ audience }}"

controller_user_accounts:
  - username: "{{ audience }}_infrastructure"
    password: "{{ ansible_password }}"
    email: dont@email.me
    update_secrets: no
  - username: "{{ audience }}_basis"
    password: "{{ ansible_password }}"
    email: dont@email.me
    update_secrets: no
  - username: "{{ audience }}_business_analyst"
    password: "{{ ansible_password }}"
    email: dont@email.me
    update_secrets: no

controller_inventories:
  - name: "{{ audience }} SAP Infrastructure"
    organization: "{{ audience }}"
    variables:
      company: "{{ audience }}"

controller_groups:
  - name: primary
    inventory: "{{ audience }} SAP Infrastructure"
    variables:
      sap_hana_hsr_role: primary
  - name: secondary
    inventory: "{{ audience }} SAP Infrastructure"
    variables:
      sap_hana_hsr_role: secondary
  - name: hana
    inventory: "{{ audience }} SAP Infrastructure"
    children:
      - primary
      - secondary
  - name: netweaver
    inventory: "{{ audience }} SAP Infrastructure"
  - name: s4hana
    inventory: "{{ audience }} SAP Infrastructure"
    children:
      - hana
      - netweaver
    variables:
      os: rhel8.4
      application: sap
  - name: production
    inventory: "{{ audience }} SAP Infrastructure"
    variables:
      lifecycle_environment: production

controller_projects:
  - name: "{{ audience }} S4HANA Deployment Code"
    organization: "{{ audience }}"
    scm_branch: main
    scm_type: git
    scm_url: https://github.com/jjaswanson4/patching-demo.git
    wait: yes

controller_templates:
  - name: Add Hosts to Controller Inventory
    inventory: Local Action Inventory
    project: "{{ audience }} S4HANA Deployment Code"
    playbook: demos/s4hana-deployment/add-hosts-to-controller.yml
    execution_environment: S4HANA Deployment Demo EE
    credentials:
      - S4HANA Deployment Peripheral Credentials


  # - name: Provision Demo Hosts | Patching Demo
  #   inventory: Patching Demo Inventory
  #   limit: demo_hosts
  #   project: Patching Demo
  #   playbook: provisioner/playbooks/provision-demo-hosts.yml
  #   execution_environment: Demo Provisioner EE
  #   credentials:
  #     - Patching Demo Provisioner Peripheral Credentials
  #     - Patching Demo Provisioner Root Account
  #   extra_vars:
  #     ansible_become: no
  # - name: Preconfigure for SAP | Patching Demo
  #   inventory: Patching Demo Inventory
  #   limit: s4hana
  #   project: Patching Demo
  #   playbook: provisioner/playbooks/sap-preconfigure.yml
  #   execution_environment: Demo Provisioner EE
  #   credentials:
  #     - Patching Demo Provisioner Peripheral Credentials
  #     - Patching Demo Provisioner Root Account
  # - name: Preconfigure for HANA Install | Patching Demo
  #   inventory: Patching Demo Inventory
  #   limit: hana
  #   project: Patching Demo
  #   playbook: provisioner/playbooks/hana-preconfigure.yml
  #   execution_environment: Demo Provisioner EE
  #   credentials:
  #     - Patching Demo Provisioner Root Account
  # - name: Preconfigure for Netweaver/S4 Install | Patching Demo
  #   inventory: Patching Demo Inventory
  #   limit: netweaver
  #   project: Patching Demo
  #   playbook: provisioner/playbooks/netweaver-preconfigure.yml
  #   execution_environment: Demo Provisioner EE
  #   credentials:
  #     - Patching Demo Provisioner Root Account
  # - name: Deploy SAP HANA | Non_Production | Patching Demo
  #   inventory: Patching Demo Inventory
  #   limit: 'hana:&non_production'
  #   project: Patching Demo
  #   playbook: provisioner/playbooks/deploy-hana.yml
  #   execution_environment: Demo Provisioner EE
  #   credentials:
  #     - Patching Demo Provisioner Root Account
  # - name: Deploy SAP HANA | Production | Patching Demo
  #   inventory: Patching Demo Inventory
  #   limit: 'hana:&production'
  #   project: Patching Demo
  #   playbook: provisioner/playbooks/deploy-hana.yml
  #   execution_environment: Demo Provisioner EE
  #   credentials:
  #     - Patching Demo Provisioner Root Account
  # - name: Install Netweaver/S4 | Non_Production | Patching Demo
  #   inventory: Patching Demo Inventory
  #   limit: 'netweaver:&non_production'
  #   project: Patching Demo
  #   playbook: provisioner/playbooks/install-s4.yml
  #   execution_environment: Demo Provisioner EE
  #   credentials:
  #     - Patching Demo Provisioner Root Account
  # - name: Install Netweaver/S4 | Production | Patching Demo
  #   inventory: Patching Demo Inventory
  #   limit: 'netweaver:&production'
  #   project: Patching Demo
  #   playbook: provisioner/playbooks/install-s4.yml
  #   execution_environment: Demo Provisioner EE
  #   credentials:
  #     - Patching Demo Provisioner Root Account
  # - name: Reinstate HSR | Patching Demo
  #   inventory: Patching Demo Inventory
  #   limit: 'hana:&primary'
  #   project: Patching Demo
  #   playbook: provisioner/playbooks/reinstate-hsr.yml
  #   execution_environment: Demo Provisioner EE
  #   credentials:
  #     - Patching Demo Provisioner Root Account

controller_workflows:
  - name: Provision S4HANA SID
    organization: "{{ audience }}"
    state: "{{ controller_state | default('present') }}"
    survey_enabled: yes
    survey:
      name: ''
      description: ''
      spec:
        - type: text
          question_name: "What is the desired SAP System Identification (SID)?"
          variable: sid
          required: yes
          default: DS4
        - type: text
          question_name: "What is the SAR file name?"
          variable: sap_hana_deployment_bundle_sar_file_name
          required: yes
          default: IMDB_SERVER20_046_0-80002031.SAR
        - type: text
          question_name: "What is the name of the SAPCAR file?"
          variable: sap_hana_deployment_sapcar_file_name
          required: yes
          default: SAPCAR_1010-70006178.EXE
        - type: text
          question_name: "What is the HANA env type?"
          variable: sap_hana_deployment_hana_env_type
          required: yes
          default: development
        - type: text
          question_name: "What is the HANA instance number?"
          variable: sap_hana_deployment_hana_instance_number
          required: yes
          default: "00"
        - type: text
          question_name: "What is the desired S4HANA product?"
          variable: "{{ sap_s4hana_deployment_product_id }}"
          default: "NW_ABAP_OneHost:S4HANA1909.CORE.HDB.ABAP"
        - type: text
          question_name: "What is the S4HANA SAPCAR file name?"
          variable: sap_s4hana_deployment_sapcar_file_name
          default: SAPCAR_1010-70006178.EXE
        - type: text
          question_name: "What is the S4HANA swpm file name?"
          variable: sap_s4hana_deployment_swpm_sar_file_name
          default: SWPM20SP04_6-80003424.SAR
        - type: text
          question_name: "How many deployment parallel jobs should run?"
          variable: sap_s4hana_deployment_parallel_jobs_nr
          default: "30"
        - type: text
          question_name: "What is the S4HANA deployment igs file name?"
          variable: sap_s4hana_deployment_parallel_jobs_nr
          default: igsexe_9-80003187.sar
        - type: text
          question_name: "What is the S4HANA deployment igs helper file name?"
          variable: sap_s4hana_deployment_igs_helper_file_name
          default: igshelper_17-10010245.sar
        - text: text
          question_name: "What is the S4HANA deployment kernel dependent file name?"
          variable: sap_s4hana_deployment_kernel_dependent_file_name
          default: SAPEXEDB_201-80003385.SAR
        - text: text
          question_name: "What is the S4HANA deployment kernel independent file name?"
          variable: sap_s4hana_deployment_kernel_independent_file_name
          default: SAPEXE_201-80003386.SAR

controller_roles:

