---

controller_organizations:
  - name: "{{ audience }}"
    galaxy_credentials:
      - MSP Lab Automation Hub - RH Certified
      - MSP Lab Automation Hub - Community
      - Ansible Galaxy

controller_execution_environments:
  - name: Compliance Demo EE
    image: 'aap20-hub.josh.lab.msp.redhat.com/compliance-demo-ee:latest'
    organization: "{{ audience }}"
    credential: MSP Lab AAP20 Automation Hub

controller_credential_types:
  - name: Console.redhat.com Credentials
    kind: cloud
    injectors:
      extra_vars:
        crhc_username: "{{ crhc_username }}"
        crhc_password: "{{ crhc_password }}"

controller_credentials:
  - name: Compliance Demo Peripheral Credentials
    credential_type: Demo Provisioner Peripheral Credentials
    organization: "{{ audience }}"
  - name: Console.redhat.com Credentials
    credential_type: Console.redhat.com Credentials
    organization: "{{ audience }}"
  - name: Compliance Root Credentials
    credential_type: Machine
    organization: "{{ audience }}"
    inputs:
      username: root
      password: "{{ ansible_password }}"
  - name: Compliance Non-Root Credentials
    credential_type: Machine
    organization: "{{ audience }}"
    inputs:
      username: root
      password: "{{ ansible_password }}"

controller_inventories:
  - name: "{{ audience }} Infrastructure"
    organization: "{{ audience }}"
    variables:
      satellite_url: https://compliance-satellite.josh.lab.msp.redhat.com
      ansible_roles:
        - theforeman.foreman_scap_client
      hostgroups:
        - name: rhel7-hipaa
          parent: rhel7
          ansible_roles: "{  { ansible_roles }}"
        - name: rhel8-hipaa
          parent: rhel8
          ansible_roles: "{  { ansible_roles }}"

controller_hosts:
  - name: compliance-satellite.josh.lab.msp.redhat.com
    inventory: "{{ audience }} Infrastructure"
    variables:
      ansible_host: 10.15.121.3
  - name: rhel7-hipaa.josh.lab.msp.redhat.com
    inventory: "{{ audience }} Infrastructure"
    variables:
      ansible_host: 10.15.121.50
  - name: rhel8-hipaa.josh.lab.msp.redhat.com
    inventory: "{{ audience }} Infrastructure"
    variables:
      ansible_host: 10.15.121.51

controller_groups:
  - name: satellite
    inventory: "{{ audience }} Infrastructure"
    hosts:
      - compliance-satellite.josh.lab.msp.redhat.com
  - name: rhel7_hipaa
    inventory: "{{ audience }} Infrastructure"
    hosts:
      - rhel7-hipaa.josh.lab.msp.redhat.com
    variables:
      hostgroup: rhel7/rhel7-hipaa
  - name: rhel8_hipaa
    inventory: "{{ audience }} Infrastructure"
    hosts:
      - rhel8-hipaa.josh.lab.msp.redhat.com
    variables:
      hostgroup: rhel8/rhel8-hipaa
  - name: rhel7
    inventory: "{{ audience }} Infrastructure"
    children:
      - rhel7_hipaa
    variables:
      os: rhel7
  - name: rhel8
    inventory: "{{ audience }} Infrastructure"
    children:
      - rhel8_hipaa
    variables:
      os: rhel8

controller_projects:
  - name: "{{ audience }} Compliance Code"
    organization: "{{ audience }}"
    scm_branch: main
    scm_type: git
    scm_url: https://github.com/jjaswanson4/patching-demo.git
    wait: yes

controller_templates:
  - name: Upload SCAP Content
    organization: "{{ audience }}"
    ask_inventory_on_launch: yes
    ask_limit_on_launch: yes
    project: "{{ audience }} Compliance Code"
    playbook: demos/compliance/playbooks/upload-scap-content.yml
    execution_environment: Compliance Demo EE
    ask_credential_on_launch: yes
  - name: Create Compliance Hostgroups
    organization: "{{ audience }}"
    ask_inventory_on_launch: yes
    ask_limit_on_launch: yes
    project: "{{ audience }} Compliance Code"
    playbook: demos/compliance/playbooks/create-compliance-hostgroups.yml
    execution_environment: Compliance Demo EE
    ask_credential_on_launch: yes
  - name: Move Hosts to Hostgroups
    organization: "{{ audience }}"
    ask_inventory_on_launch: yes
    ask_limit_on_launch: yes
    project: "{{ audience }} Compliance Code"
    playbook: demos/compliance/playbooks/move-hosts-to-hostgroups.yml
    execution_environment: Compliance Demo EE
    ask_credential_on_launch: yes

controller_workflows:
  - name: Setup Compliance
    organization: "{{ audience }}"
    state: "{{ controller_state | default('present') }}"
    extra_vars:
      demo: compliance
    simplified_workflow_nodes:
      - unified_job_template: Upload SCAP Content
        identifier: node101
        inventory: "{{ audience }} Infrastructure"
        limit: satellite
        credentials:
          - Compliance Demo Peripheral Credentials
        success_nodes:
          - node102
      - unified_job_template: Create Compliance Hostgroups
        identifier: node102
        inventory: "{{ audience }} Infrastructure"
        limit: satellite
        credentials:
          - Compliance Demo Peripheral Credentials
        success_nodes:
          - node103
      - unified_job_template: Move Hosts to Hostgroups
        identifier: node103
        inventory: "{{ audience }} Infrastructure"
        limit: rhel7:rhel8
        credentials:
          - Compliance Demo Peripheral Credentials