---

controller_organizations:
  - name: "{{ audience }}"
    galaxy_credentials:
      - MSP Lab Automation Hub - RH Certified
      - MSP Lab Automation Hub - Community
      - Ansible Galaxy

controller_credential_types:
  - name: Console.redhat.com Credentials
    kind: cloud
    injectors:
      extra_vars:
        crhc_username: "{{ crhc_username }}"
        crhc_password: "{{ crhc_password }}"

controller_credentials:
  - name: Compliance Demo Peripheral Credentials
    credential_type: Demo Provisioner Peripheral Credentials
    organization: "{{ audience }}"
  - name: Console.redhat.com Credentials
    credential_type: Console.redhat.com Credentials
    organization: "{{ audience }}"
  - name: Compliance Root Credentials
    credential_type: Machine
    organization: "{{ audience }}"
    inputs:
      username: root
      password: "{{ ansible_password }}"
  - name: Compliance Non-Root Credentials
    credential_type: Machine
    organization: "{{ audience }}"
    inputs:
      username: root
      password: "{{ ansible_password }}"

controller_templates:
  - name: Upload SCAP Content
    inventory: PCompliance Demo Infrastructure
    limit: satellite
    project: Demo Provisioner Codebase
    playbook: provisioner/demos/compliance/playbooks/upload-scap-content.yml
    execution_environment: Compliance Demo EE
    ask_credential_on_launch: yes

controller_workflows:
  - name: Setup Compliance
    organization: "{{ audience }}"
    state: "{{ controller_state | default('present') }}"
    extra_vars:
      demo: compliance
    workflow_nodes:
      - unified_job_template: Upload SCAP Content
        identifier: node101
        credentials:
          - Compliance Demo Peripheral Credentials
