---

controller_organizations:
  - name: "{{ audience }}"
    galaxy_credentials:
      - MSP Lab Automation Hub - RH Certified
      - MSP Lab Automation Hub - Community
      - Ansible Galaxy

controller_execution_environments:
  - name: Compliance Demo EE
    image: 'aap20-hub.josh.lab.msp.redhat.com/compliance-demo-ee:latest'
    organization: "{{ audience }}"
    credential: MSP Lab AAP20 Automation Hub
    pull: always
  - name: Compliance Demo Compliance EE
    image: 'aap20-hub.josh.lab.msp.redhat.com/compliance-demo-compliance-ee:1.0.0'
    organization: "{{ audience }}"
    credential: MSP Lab AAP20 Automation Hub
    pull: always

controller_credential_types:
  - name: Console.redhat.com Credentials
    kind: cloud
    injectors:
      extra_vars:
        crhc_username: "{{ crhc_username }}"
        crhc_password: "{{ crhc_password }}"

controller_credentials:
  - name: Compliance Demo Peripheral Credentials
    credential_type: Demo Provisioner Peripheral Credentials
    organization: "{{ audience }}"
  - name: Console.redhat.com Credentials
    credential_type: Console.redhat.com Credentials
    organization: "{{ audience }}"
  - name: Compliance Root Credentials
    credential_type: Machine
    organization: "{{ audience }}"
    inputs:
      username: root
      password: "{{ ansible_password }}{{ ansible_password }}"
      become_password: "{{ ansible_password }}{{ ansible_password }}"
  - name: Compliance Non-Root Credentials
    credential_type: Machine
    organization: "{{ audience }}"
    inputs:
      username: compliance-user
      password: "{{ ansible_password }}{{ ansible_password }}"

controller_inventories:
  - name: "{{ audience }} Infrastructure"
    organization: "{{ audience }}"
    variables:
      satellite_url: https://compliance-satellite.josh.lab.msp.redhat.com
      ansible_roles:
        - theforeman.foreman_scap_client
      

controller_hosts:
  - name: compliance-satellite.josh.lab.msp.redhat.com
    inventory: "{{ audience }} Infrastructure"
    variables:
      ansible_host: 10.15.121.3
  - name: rhel7-hipaa.josh.lab.msp.redhat.com
    inventory: "{{ audience }} Infrastructure"
    variables:
      ansible_host: 10.15.121.50
  - name: rhel8-hipaa.josh.lab.msp.redhat.com
    inventory: "{{ audience }} Infrastructure"
    variables:
      ansible_host: 10.15.121.51

controller_groups:
  - name: satellite
    inventory: "{{ audience }} Infrastructure"
    hosts:
      - compliance-satellite.josh.lab.msp.redhat.com
  - name: hipaa
    inventory: "{{ audience }} Infrastructure"
    hosts:
      - rhel7-hipaa.josh.lab.msp.redhat.com
      - rhel8-hipaa.josh.lab.msp.redhat.com
    variables:
      policy_name: Health Insurance Portability and Accountability Act (HIPAA)
      child_hostgroup: hipaa
      rhel7_parent_profile_id: 5d7af59d-2266-4e09-8024-07a48eb1557c
      rhel8_parent_profile_id: e5264e5d-d4b3-4c82-80a0-93448de468a7
  - name: rhel7
    inventory: "{{ audience }} Infrastructure"
    hosts:
      - rhel7-hipaa.josh.lab.msp.redhat.com
    variables:
      os: rhel7
      parent_hostgroup: rhel7
  - name: rhel8
    inventory: "{{ audience }} Infrastructure"
    hosts:
      - rhel8-hipaa.josh.lab.msp.redhat.com
    variables:
      os: rhel8
      parent_hostgroup: rhel8

controller_projects:
  - name: "{{ audience }} Compliance Code"
    organization: "{{ audience }}"
    scm_branch: main
    scm_type: git
    scm_url: https://github.com/jjaswanson4/patching-demo.git
    wait: yes

controller_templates:
  - name: Upload SCAP Content
    organization: "{{ audience }}"
    ask_inventory_on_launch: yes
    ask_limit_on_launch: yes
    project: "{{ audience }} Compliance Code"
    playbook: demos/compliance/playbooks/upload-scap-content.yml
    execution_environment: Compliance Demo EE
    ask_credential_on_launch: yes
  - name: Create Hostgroups
    organization: "{{ audience }}"
    ask_inventory_on_launch: yes
    ask_limit_on_launch: yes
    project: "{{ audience }} Compliance Code"
    playbook: demos/compliance/playbooks/create-hostgroups.yml
    execution_environment: Compliance Demo EE
    ask_credential_on_launch: yes
  - name: Move Hosts to Hostgroups
    organization: "{{ audience }}"
    ask_inventory_on_launch: yes
    ask_limit_on_launch: yes
    project: "{{ audience }} Compliance Code"
    playbook: demos/compliance/playbooks/move-hosts-to-hostgroups.yml
    execution_environment: Compliance Demo EE
    ask_credential_on_launch: yes
  - name: Create Policies on Satellite
    organization: "{{ audience }}"
    ask_inventory_on_launch: yes
    ask_limit_on_launch: yes
    project: "{{ audience }} Compliance Code"
    playbook: demos/compliance/playbooks/create-policies-on-satellite.yml
    execution_environment: Compliance Demo EE
    ask_credential_on_launch: yes
  - name: Deploy Compliance Scanning
    organization: "{{ audience }}"
    ask_inventory_on_launch: yes
    ask_limit_on_launch: yes
    project: "{{ audience }} Compliance Code"
    playbook: demos/compliance/playbooks/deploy-compliance-scanning.yml
    execution_environment: Compliance Demo EE
    ask_credential_on_launch: yes
  - name: Create Policies on Console.redhat.com
    organization: "{{ audience }}"
    ask_inventory_on_launch: yes
    ask_limit_on_launch: yes
    project: "{{ audience }} Compliance Code"
    playbook: demos/compliance/playbooks/create-policies-on-crhc.yml
    execution_environment: Compliance Demo EE
    ask_credential_on_launch: yes
  - name: Assign Hosts to Policy on Console.redhat.com
    organization: "{{ audience }}"
    ask_inventory_on_launch: yes
    ask_limit_on_launch: yes
    project: "{{ audience }} Compliance Code"
    playbook: demos/compliance/playbooks/assign-hosts-to-policy.yml
    execution_environment: Compliance Demo EE
    ask_credential_on_launch: yes
  - name: Run Compliance Scan
    organization: "{{ audience }}"
    ask_inventory_on_launch: yes
    ask_limit_on_launch: yes
    project: "{{ audience }} Compliance Code"
    playbook: demos/compliance/playbooks/run-compliance-scan.yml
    execution_environment: Compliance Demo EE
    ask_credential_on_launch: yes
    ask_variables_on_launch: yes
    become_enabled: yes
  - name: Run Compliance Roles
    organization: "{{ audience }}"
    ask_inventory_on_launch: yes
    ask_limit_on_launch: yes
    project: "{{ audience }} Compliance Code"
    playbook: demos/compliance/playbooks/run-compliance-roles.yml
    execution_environment: Compliance Demo Compliance EE
    ask_credential_on_launch: yes
    ask_variables_on_launch: yes
    become_enabled: yes
  - name: Reboot Systems
    organization: "{{ audience }}"
    ask_inventory_on_launch: yes
    ask_limit_on_launch: yes
    project: "{{ audience }} Compliance Code"
    playbook: demos/compliance/playbooks/reboot-systems.yml
    execution_environment: Compliance Demo EE
    ask_credential_on_launch: yes
    become_enabled: yes

controller_workflows:
  - name: Setup Satellite Compliance Scanning
    organization: "{{ audience }}"
    state: "{{ controller_state | default('present') }}"
    extra_vars:
      demo: compliance
      audience: "{{ audience }}"
    simplified_workflow_nodes:
      - unified_job_template: Upload SCAP Content
        identifier: node101
        inventory: "{{ audience }} Infrastructure"
        limit: satellite
        credentials:
          - Compliance Demo Peripheral Credentials
        success_nodes:
          - node102
      - approval_node:
          name: Approve 'Create Hostgroups'
        identifier: node102
        success_nodes:
          - node103
      - unified_job_template: Create Hostgroups
        identifier: node103
        inventory: "{{ audience }} Infrastructure"
        limit: rhel7:rhel8
        credentials:
          - Compliance Demo Peripheral Credentials
        success_nodes:
          - node104
      - approval_node:
          name: Approve 'Move Hosts to Hostgroups'
        identifier: node104
        success_nodes:
          - node105
      - unified_job_template: Move Hosts to Hostgroups
        identifier: node105
        inventory: "{{ audience }} Infrastructure"
        limit: rhel7:rhel8
        credentials:
          - Compliance Demo Peripheral Credentials
        success_nodes:
          - node106
      - approval_node:
          name: Approve 'Create Policies on Satellite'
        identifier: node106
        success_nodes:
          - node107
      - unified_job_template: Create Policies on Satellite
        identifier: node107
        inventory: "{{ audience }} Infrastructure"
        limit: rhel7:rhel8
        credentials:
          - Compliance Demo Peripheral Credentials
        success_nodes:
          - node108
      - approval_node:
          name: Approve 'Deploy Compliance Scanning'
        identifier: node108
        success_nodes:
          - node109
      - unified_job_template: Deploy Compliance Scanning
        identifier: node109
        inventory: "{{ audience }} Infrastructure"
        limit: rhel7:rhel8
        credentials:
          - Compliance Demo Peripheral Credentials

  - name: Setup Insights Compliance Scanning
    organization: "{{ audience }}"
    state: "{{ controller_state | default('present') }}"
    extra_vars:
      demo: compliance
      audience: "{{ audience }}"
    simplified_workflow_nodes:
      - unified_job_template: Create Policies on Console.redhat.com
        identifier: node101
        inventory: "{{ audience }} Infrastructure"
        limit: rhel7:rhel8
        credentials:
          - Console.redhat.com Credentials
          - Compliance Root Credentials
        success_nodes:
          - node102
      - approval_node:
          name: Approve 'Assign Hosts to Policy on Console.redhat.com'
        identifier: node102
        success_nodes:
          - node103
      - unified_job_template: Assign Hosts to Policy on Console.redhat.com
        identifier: node103
        inventory: "{{ audience }} Infrastructure"
        limit: rhel7:rhel8
        credentials:
          - Console.redhat.com Credentials
          - Compliance Root Credentials

  - name: Apply Compliance Automation
    organization: "{{ audience }}"
    state: "{{ controller_state | default('present') }}"
    extra_vars:
      demo: compliance
      audience: "{{ audience }}"
    simplified_workflow_nodes:
      - unified_job_template: Run Compliance Scan
        identifier: node101
        inventory: "{{ audience }} Infrastructure"
        limit: rhel7:rhel8
        credentials:
          - Compliance Non-Root Credentials
        success_nodes:
          - node102
      - approval_node:
          name: Approve 'Run Compliance Roles'
        identifier: node102
        success_nodes:
          - node103
      - unified_job_template: Run Compliance Roles
        identifier: node103
        inventory: "{{ audience }} Infrastructure"
        limit: rhel7:rhel8
        credentials:
          - Compliance Non-Root Credentials
        success_nodes:
          - node104
      - unified_job_template: Reboot Systems
        identifier: node104
        inventory: "{{ audience }} Infrastructure"
        limit: rhel7:rhel8
        credentials:
          - Compliance Non-Root Credentials
        success_nodes:
          - node105
      - unified_job_template: Run Compliance Scan
        identifier: node105
        inventory: "{{ audience }} Infrastructure"
        limit: rhel7:rhel8
        credentials:
          - Compliance Non-Root Credentials
        extra_data:
          become: yes
