---

controller_inventories:
  - name: Compliance Demo Infrastructure
    organization: Demo Provisioner
    variables:
      dns_zone: josh.lab.msp.redhat.com
      dns:
        server: idm05.lab.msp.redhat.com
        password: "{  { dns_pass }}"
        records:
          - name: "{  { inventory_hostname.split('.')[0] }}"
            zone: josh.lab.msp.redhat.com
            type: A
            value: "{  { ip_address }}"
          - name: "{  { ip_address.split('.')[-1] }}"
            zone: "{  { ip_address.split('.')[2] }}.15.10.in-addr.arpa."
            type: PTR
            value: "{  { inventory_hostname }}."
      config_files:
        - hosts
        - resolv.conf
      timesync_ntp_servers:
        - hostname: 0.rhel.pool.ntp.org
          iburst: yes
        - hostname: 1.rhel.pool.ntp.org
          iburst: yes
        - hostname: 2.rhel.pool.ntp.org
          iburst: yes
        - hostname: 3.rhel.pool.ntp.org
          iburst: yes
      vcenter:
        server: vcenter02.lab.msp.redhat.com
        username: 'Administrator@vsphere.local'
        password: "{  { vcenter_password }}"
        datacenter: MSP Lab
      selinux_policy: targeted
      selinux_state: permissive
      dns_resolv:
        search_domains:
          - josh.lab.msp.redhat.com
          - lab.msp.redhat.com
        nameservers:
          - 10.15.120.4
          - 10.15.108.5
        options:
          - 'timeout:1'
      base_packages:
        disable_gpg_check: yes
        packages:
          - lsof
          - vim
          - sos
          - redhat-support-tool
          - "{  { htop_url }}"
      ignore_virtual_disk_errors: yes
      remove_cdrom: no

controller_hosts:
  - name: compliance-satellite.josh.lab.msp.redhat.com
    inventory: Compliance Demo Infrastructure
    variables: "{{ lookup('file', 'demos/compliance/vars/satellite-configuration.yml') | from_yaml }}"
  - name: compliance-deployment-demo
    inventory: Local Action Inventory
    variables: "{{ lookup('file', 'demos/compliance/vars/controller-configuration.yml') | from_yaml }}"
  - name: rhel7-hipaa.josh.lab.msp.redhat.com
    inventory: Compliance Demo Infrastructure
    variables:
      ansible_host: 10.15.121.50
      ip_address: "{  { ansible_host }}"
  - name: rhel8-hipaa.josh.lab.msp.redhat.com
    inventory: Compliance Demo Infrastructure
    variables:
      ansible_host: 10.15.121.51
      ip_address: "{  { ansible_host }}" 
    
controller_groups:
  - name: satellite
    inventory: Compliance Demo Infrastructure
    hosts:
      - compliance-satellite.josh.lab.msp.redhat.com
  - name: management_plane
    inventory: Compliance Demo Infrastructure
    variables:
      lifecycle_environment: production
      provisioning:
        satellite:
          server: satellite06.lab.msp.redhat.com
          username: admin
          password: "{  { satellite_password }}"
        host_group: "{  { os }}"
        organization: MSP Lab
        location: MSP Lab
        method: bootdisk
        dns_domain: josh.lab.msp.redhat.com
        cpus: "{  { cpus }}"
        memory_mb: "{  { memory_mb }}"
        activation_keys: "ak-{  { application }}-{  { os }}-{  { lifecycle_environment }}"
    children:
      - satellite
  - name: rhel7
    inventory: Compliance Demo Infrastructure
    hosts:
      - rhel7-hipaa.josh.lab.msp.redhat.com
    variables:
      os: rhel7
      htop_url: https://dl.fedoraproject.org/pub/epel/7/x86_64/Packages/h/htop-2.2.0-3.el7.x86_64.rpm
  - name: rhel8
    inventory: Compliance Demo Infrastructure
    hosts:
      - rhel8-hipaa.josh.lab.msp.redhat.com
    variables:
      os: rhel8
      htop_url: https://dl.fedoraproject.org/pub/epel/8/Everything/x86_64/Packages/h/htop-3.0.5-1.el8.x86_64.rpm
  - name: demo_hosts
    inventory: Compliance Demo Infrastructure
    children:
      - rhel7
      - rhel8
    variables:
      cpus: 2
      memory_mb: 4096
      application: general
      lifecycle_environment: production
      run_additional_roles: no
      firewall:
        name: firewalld
        state: stopped
        enabled: no
      provisioning:
        satellite:
          server: compliance-satellite.josh.lab.msp.redhat.com
          username: admin
          password: "{  { ansible_password }}"
        host_group: "{  { os }}"
        organization: "{  { audience }}"
        location: "{  { audience }}"
        method: bootdisk
        dns_domain: josh.lab.msp.redhat.com
        cpus: "{  { cpus }}"
        memory_mb: "{  { memory_mb }}"
        activation_keys: "ak-{  { application }}-{  { os }}-{  { lifecycle_environment }}"

controller_workflows:
  - name: Provision Compliance Demo
    organization: Demo Provisioner
    state: "{{ controller_state | default('present') }}"
    extra_vars:
      demo: compliance
    survey_enabled: yes
    survey:
      name: ''
      description: ''
      spec:
        - type: text
          question_name: "Demo Audience?"
          question_description: "Who is the audience for this demo?"
          variable: audience
          required: yes
        - type: text
          question_name: "Provisioner?"
          question_description: "Who is provisioning this demo?"
          variable: provisioner
          required: yes
          default: 'Josh Swanson'
        - type: text
          question_name: "Provisioner's Email?"
          question_description: "What is the provisioner's email address?"
          variable: provisioner_email
          required: yes
          default: 'joshswanson@redhat.com'
        - type: multiplechoice
          question_name: Deploy Satellite?
          question_description: Should satellite be deployed?
          variable: deploy_satellite
          choices:
            - "yes"
            - "no"
          default: "yes"
          required: yes
        - type: multiplechoice
          question_name: Configure controller?
          question_description: Should controller be configured?
          variable: configure_controller
          choices:
            - "yes"
            - "no"
          default: "yes"
          required: yes
        - type: multiplechoice
          question_name: Provision demo hosts?
          question_description: Should the demo hosts be provisioned?
          variable: provision_demo_hosts
          choices:
            - "yes"
            - "no"
          default: "yes"
          required: yes           
    simplified_workflow_nodes:
    # Work nodes
      - unified_job_template: Configure Ansible Controller
        identifier: node101
        limit: compliance-deployment-demo
        credentials:
          - Demo Provisioner Peripheral Credentials
        success_nodes:
          - node999
        failure_nodes:
          - node201
      - unified_job_template: Setup Red Hat Satellite
        identifier: node102
        inventory: Compliance Demo Infrastructure
        limit: satellite
        credentials:
          - Demo Provisioner Peripheral Credentials
          - Demo Provisioner Root Account
        success_nodes:
          - node103
        failure_nodes:
          - node202
      - unified_job_template: Provision Systems
        identifier: node103
        inventory: Compliance Demo Infrastructure
        limit: demo_hosts
        credentials:
          - Demo Provisioner Peripheral Credentials
          - Demo Provisioner Root Account
        success_nodes:
          - node999
        failure_nodes:
          - node203
    # Notification Nodes
      - unified_job_template: Send Provisioner Email | Succeeded
        identifier: node999
        all_parents_must_converge: yes
      - unified_job_template: Send Provisioner Email | Failed
        identifier: node201
      - unified_job_template: Send Provisioner Email | Failed
        identifier: node202
      - unified_job_template: Send Provisioner Email | Failed
        identifier: node203
  - name: Teardown Compliance Demo
    organization: Demo Provisioner
    state: "{{ controller_state | default('present') }}"
    extra_vars:
      demo: compliance
    survey_enabled: yes
    survey:
      name: ''
      description: ''
      spec:
        - type: text
          question_name: "Demo Audience?"
          question_description: "Who is the audience for this demo"
          variable: audience
          required: yes
    simplified_workflow_nodes:
      - unified_job_template: Remove Controller Configuration
        identifier: node995
        limit: compliance-demo
        credentials:
          - Demo Provisioner Peripheral Credentials
        always_nodes:
          - node997
      - unified_job_template: Unregister from Insights
        identifier: node996
        inventory: Compliance Demo Infrastructure
        limit: 'demo_hosts:satellite'
        credentials:
          - Demo Provisioner Root Account
        always_nodes:
          - node997
      - unified_job_template: Teardown Systems
        identifier: node997
        inventory: Compliance Demo Infrastructure
        limit: demo_hosts
        credentials:
          - Demo Provisioner Peripheral Credentials
        always_nodes:
          - node998
      - unified_job_template: Teardown Systems
        identifier: node998
        inventory: Compliance Demo Infrastructure
        limit: satellite
        credentials:
          - Demo Provisioner Peripheral Credentials
        always_nodes:
          - node999
      - unified_job_template: Cleanup DNS Records
        identifier: node999
        inventory: Compliance Demo Infrastructure
        limit: 'demo_hosts:satellite'
        credentials:
          - Demo Provisioner Peripheral Credentials
  - name: Reset Compliance Demo
    organization: Demo Provisioner
    state: "{{ controller_state | default('present') }}"
    extra_vars:
      demo: compliance
    survey_enabled: yes
    survey:
      name: ''
      description: ''
      spec:
        - type: text
          question_name: "Demo Audience?"
          question_description: "Who is the audience for this demo"
          variable: audience
          required: yes
    simplified_workflow_nodes:
      - unified_job_template: Unregister from Insights
        identifier: node101
        inventory: Compliance Demo Infrastructure
        limit: demo_hosts
        credentials:
          - Demo Provisioner Root Account
        always_nodes:
          - node102
          - node103
      - unified_job_template: Teardown Systems
        identifier: node102
        inventory: Compliance Demo Infrastructure
        limit: demo_hosts
        credentials:
          - Demo Provisioner Peripheral Credentials
      - unified_job_template: Cleanup DNS Records
        identifier: node103
        inventory: Compliance Demo Infrastructure
        limit: demo_hosts
        credentials:
          - Demo Provisioner Peripheral Credentials
