---

# By default, the org 'Demo Provisioner' is created and resources are configured there,
# Use this variable to override this behavior.
# For example, overriding to 'Default' will put the resources into the default controller organization.
controller_organization: Demo Provisioner

# This is the default project name. It is a var so demos can import specific job templates and override the project locally.
# Change this to change the name of the project for the provisioner job templates.
project: Demo Provisioner Codebase

# This is the default prefix for assets created for this demo.
# Change this variable to use a different prefix.
demo_prefix: Compliance Demo

# This is the realitive path to the vars files for this demo.
# Typically this contains a vars file for the provisioner, Satellite, and Controller.
vars_files_path: demos/compliance/vars

# This is the inventory that stores the information about the infrastructure needed for the demo.
# This is commonly an instance of Satellite, Controller, and some "demo hosts".
inventory: "{{ demo_prefix }} Infrastructure"

# This is the execution environment used for this demo provisioner.
# This execution environment will automatically be configured in Controller.
execution_environment:
  name: Demo Provisioner EE
  image: patching-demo-provisioner-ee

# This is the information used for the instance of Controller for the demo.
# This can be the same instance as where the provisioner is deployed, but it's not recommended.
controller:
  hostname: compliance-controller.josh.lab.msp.redhat.com
  configuration_file: "{{ vars_files_path }}/controller-configuration.yml"
  ip_address: 10.15.121.13
  username: admin
  password: "{{ controller_password }}"

# This is the information used for the instance of Satellite for the demo.
# This can be the same instance as where the provisioner is deployed, but it's not recommended.
satellite:
  hostname: compliance-satellite.josh.lab.msp.redhat.com
  configuration_file: "{{ vars_files_path }}/satellite-configuration.yml"
  ip_address: 10.15.121.3
  username: admin
  password: "{{ satellite_password }}"

# These are where demo specific components are defined, in hash form. These will automatically be added to the common resources.
# If there is no need for a specific, resource, simply define an empty var, such as `controller_organizations: []`
controller_organizations: []
controller_credential_types: []
controller_credentials: []
controller_execution_environments: []
controller_inventories: []
controller_projects: []

controller_hosts:
  - name: rhel7-hipaa.josh.lab.msp.redhat.com
    inventory: "{{ inventory }}"
    variables:
      ansible_host: 10.15.121.50
      ip_address: "{  { ansible_host }}"
  - name: rhel8-hipaa.josh.lab.msp.redhat.com
    inventory: "{{ inventory }}"
    variables:
      ansible_host: 10.15.121.51
      ip_address: "{  { ansible_host }}"
  - name: rhel7-pci.josh.lab.msp.redhat.com
    inventory: "{{ inventory }}"
    variables:
      ansible_host: 10.15.121.52
      ip_address: "{  { ansible_host }}"
  - name: rhel8-pci.josh.lab.msp.redhat.com
    inventory: "{{ inventory }}"
    variables:
      ansible_host: 10.15.121.53
      ip_address: "{  { ansible_host }}" 

controller_groups:
  - name: rhel7
    inventory: Compliance Demo Infrastructure
    hosts:
      - rhel7-hipaa.josh.lab.msp.redhat.com
      - rhel7-pci.josh.lab.msp.redhat.com
    variables:
      os: rhel7
      htop_url: https://dl.fedoraproject.org/pub/epel/7/x86_64/Packages/h/htop-2.2.0-3.el7.x86_64.rpm
  - name: rhel8
    inventory: Compliance Demo Infrastructure
    hosts:
      - rhel8-hipaa.josh.lab.msp.redhat.com
      - rhel8-pci.josh.lab.msp.redhat.com
    variables:
      os: rhel8
      htop_url: https://dl.fedoraproject.org/pub/epel/8/Everything/x86_64/Packages/h/htop-3.0.5-1.el8.x86_64.rpm
  - name: demo_hosts
    inventory: Compliance Demo Infrastructure
    children:
      - rhel7
      - rhel8
    variables:
      cpus: 2
      memory_mb: 4096
      application: general
      lifecycle_environment: production
      run_additional_roles: no
      firewall:
        name: firewalld
        state: stopped
        enabled: no
      provisioning:
        satellite:
          server: compliance-satellite.josh.lab.msp.redhat.com
          username: admin
          password: "{  { ansible_password }}"
        host_group: "{  { os }}"
        organization: "{  { audience }}"
        location: "{  { audience }}"
        method: bootdisk
        dns_domain: josh.lab.msp.redhat.com
        cpus: "{  { cpus }}"
        memory_mb: "{  { memory_mb }}"
        activation_keys: "ak-{  { application }}-{  { os }}-{  { lifecycle_environment }}"

controller_templates:
  - name: Create Compliance User
    organization: "{{ controller_organization }}"
    ask_inventory_on_launch: yes
    ask_limit_on_launch: yes
    project: "{{ project }}"
    playbook: provisioner/demos/compliance/playbooks/create-compliance-user.yml
    execution_environment: Demo Provisioner EE
    ask_credential_on_launch: yes

controller_workflows:
  - name: Provision Compliance Demo
    organization: Demo Provisioner
    state: "{{ controller_state | default('present') }}"
    extra_vars:
      demo: compliance
    survey_enabled: yes
    survey: "{{ lookup('file', '../resources/controller/provisioner-workflow-survey.yml') | from_yaml }}"          
    simplified_workflow_nodes:
      - unified_job_template: Provision Systems
        identifier: node101
        inventory: "{{ inventory }}"
        limit: satellite
        credentials:
          - "{{ demo_prefix }} Peripheral Credentials"
          - "{{ demo_prefix }} Root Account"
        success_nodes:
          - node102
        failure_nodes:
          - node1101
      - unified_job_template: Install Red Hat Satellite
        identifier: node102
        inventory: "{{ inventory }}"
        limit: satellite
        credentials:
          - "{{ demo_prefix }} Peripheral Credentials"
          - "{{ demo_prefix }} Root Account"
        success_nodes:
          - node103
        failure_nodes:
          - node1102
      - unified_job_template: Configure Red Hat Satellite
        identifier: node103
        inventory: "{{ inventory }}"
        limit: satellite
        credentials:
          - "{{ demo_prefix }} Peripheral Credentials"
          - "{{ demo_prefix }} Root Account"
        success_nodes:
          - node301
        failure_nodes:
          - node1103
      - unified_job_template: Provision Systems
        identifier: node201
        inventory: "{{ inventory }}"
        limit: controller
        credentials:
          - "{{ demo_prefix }} Peripheral Credentials"
          - "{{ demo_prefix }} Root Account"
        success_nodes:
          - node202
        failure_nodes:
          - node1201
      - unified_job_template: Install Ansible Controller
        identifier: node202
        inventory: "{{ inventory }}"
        limit: controller
        credentials:
          - "{{ demo_prefix }} Peripheral Credentials"
          - "{{ demo_prefix }} Root Account"
        success_nodes:
          - node203
        failure_nodes:
          - node1202
      - unified_job_template: Configure Ansible Controller
        identifier: node203
        inventory: "{{ inventory }}"
        limit: controller
        credentials:
          - "{{ demo_prefix }} Peripheral Credentials"
          - "{{ demo_prefix }} Root Account"
        success_nodes:
          - node999
        failure_nodes:
          - node1203
      - unified_job_template: Provision Systems
        identifier: node301
        inventory: "{{ inventory }}"
        limit: demo_hosts
        credentials:
          - "{{ demo_prefix }} Peripheral Credentials"
          - "{{ demo_prefix }} Root Account"
        success_nodes:
          - node302
        failure_nodes:
          - node1301
      - unified_job_template: Create Compliance User
        identifier: node302
        inventory: "{{ inventory }}"
        limit: demo_hosts
        credentials:
          - "{{ demo_prefix }} Peripheral Credentials"
          - "{{ demo_prefix }} Root Account"
        success_nodes:
          - node999
        failure_nodes:
          - node1302
      - unified_job_template: Send Provisioner Email
        identifier: node999
        all_parents_must_converge: yes
        extra_data:
          provisioner_status: success
      - unified_job_template: Send Provisioner Email
        identifier: node1101
        extra_data:
          provisioner_status: failed
      - unified_job_template: Send Provisioner Email
        identifier: node1102
        extra_data:
          provisioner_status: failed
      - unified_job_template: Send Provisioner Email
        identifier: node1103
        extra_data:
          provisioner_status: failed
      - unified_job_template: Send Provisioner Email
        identifier: node1201
        extra_data:
          provisioner_status: failed
      - unified_job_template: Send Provisioner Email
        identifier: node1202
        extra_data:
          provisioner_status: failed
      - unified_job_template: Send Provisioner Email
        identifier: node1203
        extra_data:
          provisioner_status: failed
      - unified_job_template: Send Provisioner Email
        identifier: node1301
        extra_data:
          provisioner_status: failed
      - unified_job_template: Send Provisioner Email
        identifier: node1302
        extra_data:
          provisioner_status: failed
  - name: Teardown Compliance Demo
    organization: Demo Provisioner
    state: "{{ controller_state | default('present') }}"
    extra_vars:
      demo: compliance
    survey_enabled: yes
    survey:
      name: ''
      description: ''
      spec:
        - type: text
          question_name: "Demo Audience?"
          question_description: "Who is the audience for this demo"
          variable: audience
          required: yes
    simplified_workflow_nodes:
      - unified_job_template: Unregister from Insights
        identifier: node996
        inventory: Compliance Demo Infrastructure
        limit: 'demo_hosts:satellite:controller'
        credentials:
          - "{{ demo_prefix }} Root Account"
        always_nodes:
          - node997
      - unified_job_template: Teardown Systems
        identifier: node997
        inventory: Compliance Demo Infrastructure
        limit: demo_hosts
        credentials:
          - "{{ demo_prefix }} Peripheral Credentials"
        always_nodes:
          - node998
      - unified_job_template: Teardown Systems
        identifier: node998
        inventory: Compliance Demo Infrastructure
        limit: management_plane
        credentials:
          - "{{ demo_prefix }} Peripheral Credentials"
        always_nodes:
          - node999
      - unified_job_template: Cleanup DNS Records
        identifier: node999
        inventory: Compliance Demo Infrastructure
        limit: 'demo_hosts:satellite:controller'
        credentials:
          - "{{ demo_prefix }} Peripheral Credentials"
  # - name: Reset Compliance Demo
  #   organization: Demo Provisioner
  #   state: "{{ controller_state | default('present') }}"
  #   extra_vars:
  #     demo: compliance
  #   survey_enabled: yes
  #   survey:
  #     name: ''
  #     description: ''
  #     spec:
  #       - type: text
  #         question_name: "Demo Audience?"
  #         question_description: "Who is the audience for this demo"
  #         variable: audience
  #         required: yes
  #   simplified_workflow_nodes:
  #     - unified_job_template: Unregister from Insights
  #       identifier: node101
  #       inventory: Compliance Demo Infrastructure
  #       limit: demo_hosts
  #       credentials:
  #         - Demo Provisioner Root Account
  #       always_nodes:
  #         - node102
  #         - node103
  #     - unified_job_template: Teardown Systems
  #       identifier: node102
  #       inventory: Compliance Demo Infrastructure
  #       limit: demo_hosts
  #       credentials:
  #         - Demo Provisioner Peripheral Credentials
  #     - unified_job_template: Cleanup DNS Records
  #       identifier: node103
  #       inventory: Compliance Demo Infrastructure
  #       limit: demo_hosts
  #       credentials:
  #         - Demo Provisioner Peripheral Credentials
