---

ansible_host: 10.15.121.3
ip_address: "{{ ansible_host }}"
cpus: 8
memory_mb: 24576
os: rhel7
application: general

htop_url: https://dl.fedoraproject.org/pub/epel/7/x86_64/Packages/h/htop-2.2.0-3.el7.x86_64.rpm

additional_storage:
  - size: 1000Gb
    type: thin
    scsi_controller: 0
    unit_number: 1

lvm:
  vg: os
  pvs: /dev/sda2,/dev/sdb

ignore_compute_resource_errors: true

satellite:
  admin_username: admin
  admin_password: "{{ satellite_password }}"
  version: 6.9
  logical_volumes:
    - name: cache
      size: 20
      path: /var/cache/pulp
    - name: pulp
      size: 500
      path: /var/lib/pulp
    - name: mongodb
      size: 100
      path: /var/lib/mongodb
    - name: qpidd
      size: 20
      path: /var/lib/qpidd
    - name: varlog
      size: 10
      path: /var/log
    - name: pqsql
      size: 100
      path: /var/opt/rh/rh-postgresql12/lib/pgsql
    - name: squid
      size: 10
      path: /var/spool/squid
    - name: usr
      size: 8
      path: /usr
    - name: opt
      size: 8
      path: /opt
    - name: puppetlabs
      size: 1
      path: /opt/puppetlabs
    - name: var
      size: 12
      path: /var
  installer_options:
    - "--foreman-proxy-plugin-remote-execution-ssh-install-key true"
    - "--foreman-proxy-dns true"
  foreman:
    organizations:
      - name: "{{ audience }}"
        initial_organization: yes
    locations:
      - name: "{{ audience }}"
        initial_location: yes
        organizations:
          - name: "{{ audience }}"
    settings:
      - name: default_download_policy
        value: on_demand
      - name: default_proxy_download_policy
        value: on_demand
      - name: unregister_delete_host
        value: true
      - name: entries_per_page
        value: 100
      - name: allow_auto_inventory_upload
        value: yes
      - name: destroy_vm_on_host_delete
        value: yes
    compute_resources:
      - name: vcenter02.lab.msp.redhat.com
        provider: vmware
        provider_params:
          url: vcenter02.lab.msp.redhat.com
          user: 'Administrator@vsphere.local'
          password: "{{ vcenter_password }}"
          datacenter: MSP Lab
        organizations:
          - name: "{{ audience }}"
        locations:
          - name: "{{ audience }}"
    compute_profiles:
      - name: general-vlan146
        compute_resource: vcenter02.lab.msp.redhat.com
        vm_attrs:
          cpus: 4
          corespersocket: 4
          memory_mb: 4096
          firmware: bios
          cluster: General
          resource_pool: Resources
          path: /Datacenters/MSP Lab/vm
          guest_id: rhel7_64Guest
          hardware_version: vmx-13
          memoryHotAddEnabled: 1
          cpuHotAddEnabled: 1
          add_cdrom: 0
          scsi_controllers:
          - type: ParaVirtualSCSIController
            key: 1000
          interfaces_attributes:
            0:
              type: VirtualVmxnet3
              network: dvportgroup-1017
          volumes_attributes:
            0:
              thin: true
              name: Hard disk
              mode: persistent
              controller_key: 1000
              size_gb: 100
              datastore: storage04-nfs-lun0
    domains:
      - name: josh.lab.msp.redhat.com
        organizations:
          - name: "{{ audience }}"
        locations:
          - name: "{{ audience }}"
    subnets:
      - name: VLAN146
        network: 10.15.120.0
        mask: 255.255.252.0
        gateway: 10.15.123.254
        dns_primary: 10.15.121.3
        dns_secondary: 10.15.108.148
        ipam: None
        boot_mode: Static
        organizations:
          - name: "{{ audience }}"
        locations:
          - name: "{{ audience }}"
        domains:
          - name: josh.lab.msp.redhat.com
    hostgroups:
      - name: rhel7
        architecture: x86_64
        compute_profile: general-vlan146
        compute_resource: vcenter02.lab.msp.redhat.com
        content_source: "{{ inventory_hostname }}"
        content_view: composite-rhel7
        domain: josh.lab.msp.redhat.com
        lifecycle_environment: Production
        operatingsystem: RHEL Server 7.9
        ptable: RHEL7 Kickstart Partition Table
        organization_of_content_source: "{{ audience }}"
        organizations:
          - "{{ audience }}"
        locations:
          - "{{ audience }}"
        subnet: VLAN146
        pxe_loader: None
        root_pass: "{{ ansible_password }}"
        kickstart_repository: Red Hat Enterprise Linux 7 Server Kickstart x86_64 7.9
      - name: rhel8
        architecture: x86_64
        compute_profile: general-vlan146
        compute_resource: vcenter02.lab.msp.redhat.com
        content_source: "{{ inventory_hostname }}"
        content_view: composite-rhel8
        domain: josh.lab.msp.redhat.com
        lifecycle_environment: Production
        operatingsystem: RedHat-8.4
        ptable: RHEL8 Kickstart Partition Table
        organization_of_content_source: "{{ audience }}"
        organizations:
          - "{{ audience }}"
        locations:
          - "{{ audience }}"
        subnet: VLAN146
        pxe_loader: None
        root_pass: "{{ ansible_password }}"
        kickstart_repository: Red Hat Enterprise Linux 8 for x86_64 - BaseOS Kickstart 8.4
    operating_systems:
      - name: RHEL Server 7.9
        ptable:
          - name: Kickstart default
          - name: RHEL7 Kickstart Partition Table
        update_existing: true
        update_args: --partition-tables "RHEL7 Kickstart Partition Table,Kickstart default"
      - name: RedHat-8.4
        ptable:
          - name: Kickstart default
          - name: RHEL8 Kickstart Partition Table
        update_existing: true
        update_args: --partition-tables "RHEL8 Kickstart Partition Table,Kickstart default"
    partition_tables:
      - name: RHEL7 Kickstart Partition Table
        file: ../demos/common/files/rhel8-ptable.erb
        os_family: Redhat
        organizations:
          - name: "{{ audience }}"
        locations:
          - name: "{{ audience }}"
      - name: RHEL8 Kickstart Partition Table
        file: ../demos/common/files/rhel8-ptable.erb
        os_family: Redhat
        organizations:
          - name: "{{ audience }}"
        locations:
          - name: "{{ audience }}"
  katello:
    - organization_name: "{{ audience }}"
      state: present
      manifest: "/tmp/satellite-manifest.zip"
      repo_sync_attempts: 1
      lifecycle_environments:
        - name: Production
          prior: Library
      content_views:
        - name: cv-kickstart-rhel8.4
          repos:
            - repo: Red Hat Enterprise Linux 8 for x86_64 - AppStream (Kickstart)
              product: Red Hat Enterprise Linux for x86_64
              releasever: 8.4
            - repo: Red Hat Enterprise Linux 8 for x86_64 - BaseOS (Kickstart)
              product: Red Hat Enterprise Linux for x86_64
              releasever: 8.4
        - name: cv-ansible-rhel8
          repos:
            - repo: Red Hat Ansible Engine 2 for RHEL 8 x86_64 (RPMs)
              product: Red Hat Ansible Engine
        - name: cv-server-rhel8
          repos:
            - repo: Red Hat Enterprise Linux 8 for x86_64 - BaseOS (RPMs)
              product: Red Hat Enterprise Linux for x86_64
              releasever: 8
        - name: cv-appstream-rhel8
          repos:
            - repo: Red Hat Enterprise Linux 8 for x86_64 - AppStream (RPMs)
              product: Red Hat Enterprise Linux for x86_64
              releasever: 8
        - name: cv-satellitetools6.9-rhel8
          repos:
            - repo: Red Hat Satellite Tools 6.9 for RHEL 8 x86_64 (RPMs)
              product: Red Hat Enterprise Linux for x86_64
        - name: cv-server-rhel7
          repos:
            - repo: Red Hat Enterprise Linux 7 Server (RPMs)
              product: Red Hat Enterprise Linux Server
              releasever: 7Server
              basearch: x86_64
        - name: cv-kickstart-rhel7.9
          repos:
            - repo: Red Hat Enterprise Linux 7 Server (Kickstart)
              product: Red Hat Enterprise Linux Server
              releasever: 7.9
              basearch: x86_64
        - name: cv-satellitetools6.9-rhel7
          repos:
            - repo: Red Hat Satellite Tools 6.8 (for RHEL 7 Server) (RPMs)
              product: Red Hat Enterprise Linux Server
              basearch: x86_64     
      composite_content_views:
        - name: composite-rhel8
          auto_publish: false
          component_content_views:
            - name: cv-kickstart-rhel8.4
            - name: cv-ansible-rhel8
            - name: cv-server-rhel8
            - name: cv-appstream-rhel8
            - name: cv-satellitetools6.9-rhel8
        - name: composite-rhel7
          auto_publish: false
          component_content_views:
            - name: cv-server-rhel7
            - name: cv-kickstart-rhel7.9
            - name: cv-satellitetools6.9-rhel7        
      activation_keys:
        - name: ak-general-rhel7-production
          lifecycle_environment: Production
          content_view: composite-rhel7
          release_version: 7Server
          content_overrides:
            - label: rhel-7-server-rpms
            - label: rhel-7-server-satellite-tools-6.9-rpms
        - name: ak-general-rhel8-production
          lifecycle_environment: Production
          content_view: composite-rhel8
          release_version: 8
          content_overrides:
            - label: satellite-tools-6.9-for-rhel-8-x86_64-rpms
            - label: rhel-8-for-x86_64-baseos-rpms
            - label: rhel-8-for-x86_64-appstream-rpms          