---

- name: setup trust between AD and IDM
  hosts:
    - all
  tasks:
    - name: create one-way trust with AD
      freeipa.ansible_freeipa.ipatrust:
        ipaadmin_password: "{{ ipaadmin_password }}"
        realm: "{{ hostvars['server2016-ad1.ad.josh.lab.msp.redhat.com']['dns_zone'] }}"
        admin: "{{ hostvars['server2016-ad1.ad.josh.lab.msp.redhat.com']['ansible_user'] }}"
        password: "{{ ansible_password }}"