---

- name: setup trust between AD and IDM
  hosts:
    - all
  pre_tasks:
    - name: set AD auth facts
      ansible.builtin.set_fact:
        domain_administrator_username: "Administrator@{{ hostvars['ad-dc1.ad.josh.lab.msp.redhat.com']['dns_zone'] }}"
  tasks:
    - name: create one-way trust with AD
      freeipa.ansible_freeipa.ipatrust:
        ipaadmin_password: "{{ ipaadmin_password }}"
        realm: "{{ hostvars['ad-dc1.ad.josh.lab.msp.redhat.com']['dns_zone'] }}"
        admin: "{{ domain_administrator_username }}"
        password: "{{ ansible_password }}"