---

- name: configure controller
  hosts:
    - all
  gather_facts: no
  vars_files:
    - vars/controller-configuration.yml 
  tasks:
    - name: include roles
      ansible.builtin.include_role:
        name: "{{ role }}"
      loop_control:
        loop_var: role
      loop:
        - redhat_cop.controller_configuration.organizations
        - redhat_cop.controller_configuration.credentials
        - redhat_cop.controller_configuration.execution_environments
        - redhat_cop.controller_configuration.teams
        - redhat_cop.controller_configuration.users
        - redhat_cop.controller_configuration.inventories
        - redhat_cop.controller_configuration.hosts
        - redhat_cop.controller_configuration.groups
        - redhat_cop.controller_configuration.projects
        - redhat_cop.controller_configuration.job_templates
        - redhat_cop.controller_configuration.workflow_job_templates
        - redhat_cop.controller_configuration.roles
      when:
        - configure_controller | bool