---

- name: provision managed hosts
  hosts:
    - all
  gather_facts: no
  pre_tasks:
    - name: add host and custom DNS entries
      ansible.builtin.set_fact:
        dns:
          server: "{{ dns.server }}"
          password: "{{ dns_pass }}"
          records: "{{ dns.records  + custom_dns_records }}"
  tasks:
    - name: include roles
      ansible.builtin.include_role:
        name: "{{ role }}"
      loop_control:
        loop_var: role
      loop:
        - jjaswanson4.utilities.idm_dns_records
        - jjaswanson4.utilities.provision_via_satellite
        - jjaswanson4.utilities.stop_networkmanager_dns
        - jjaswanson4.utilities.common_config
        - jjaswanson4.utilities.add_virtual_disk
        - jjaswanson4.utilities.mount_nfs_shares
        - redhat.rhel_system_roles.selinux
        - redhat.rhel_system_roles.timesync
        - redhat.rhel_system_roles.storage
        - linux-system-roles.cockpit
        - linux-system-roles.metrics
        - sap-preconfigure
        - redhat_sap.sap_hostagent
      when:
        - provision_demo_hosts | bool
  post_tasks:
    - name: check if reboot is required
      ansible.builtin.shell: yum needs-restarting -r
      changed_when: false
      ignore_errors: true
      register: reboot_needed
    - name: reboot system
      ansible.builtin.reboot:
      when:
        - reboot_needed.rc | int != 0