---

- name: setup hana clusters
  hosts:
    - hana
  pre_tasks:
    - name: run sap-hana-preconfigure role
      ansible.builtin.include_role:
        name: sap-hana-preconfigure
    - name: check if reboot is required
      ansible.builtin.shell: yum needs-restarting -r
      changed_when: false
      ignore_errors: true
      register: reboot_needed
    - name: reboot system
      ansible.builtin.reboot:
      when:
        - reboot_needed.rc | int != 0
  roles:  
    - redhat_sap.sap_hana_deployment
    - sap-hana-hsr
    - redhat_sap.sap_hana_ha_pacemaker