---

- name: prep for hana install
  hosts:
    - all
  roles:
    - sap-hana-preconfigure
  handlers:
    - name: reboot system
      ansible.builtin.reboot:
      listen:
      - __sap_hana_preconfigure_reboot_handler