---

- name: validate selected demo
  hosts:
    - localhost
  gather_facts: no
  vars_files:
    - demos/common/vars/demos.yml
  tasks:
    - name: validate selected demo is available
      ansible.builtin.assert:
        that:
          - demo in available_demos
        success_msg: "{{ demo }} demo selected"
        fail_msg: "selected demo {{ demo }} is not available, please select one of: {{ available_demos | join(', ') }}"

- name: apply common provisioner configuration to ansible controller
  hosts:
    - localhost
  gather_facts: no
  vars_files:
    - demos/common/vars/provisioner-configuration.yml
  roles:
    - redhat_cop.controller_configuration.organizations
    - redhat_cop.controller_configuration.credential_types
    - redhat_cop.controller_configuration.credentials
    - redhat_cop.controller_configuration.execution_environments
    - redhat_cop.controller_configuration.inventories
    - redhat_cop.controller_configuration.hosts
    - redhat_cop.controller_configuration.groups
    - redhat_cop.controller_configuration.projects
    - redhat_cop.controller_configuration.job_templates
    - redhat_cop.controller_configuration.workflow_job_templates
    - redhat_cop.controller_configuration.users
    - redhat_cop.controller_configuration.teams
    - redhat_cop.controller_configuration.roles

- name: apply {{ demo }} demo provisioner configuration to ansible controller
  hosts:
    - localhost
  gather_facts: no
  vars_files:
    - "demos/{{ demo }}/vars/provisioner-configuration.yml" 
  roles:
    - redhat_cop.controller_configuration.organizations
    - redhat_cop.controller_configuration.credential_types
    - redhat_cop.controller_configuration.credentials
    - redhat_cop.controller_configuration.execution_environments
    - redhat_cop.controller_configuration.inventories
    - redhat_cop.controller_configuration.hosts
    - redhat_cop.controller_configuration.groups
    - redhat_cop.controller_configuration.projects
    - redhat_cop.controller_configuration.job_templates
    - redhat_cop.controller_configuration.workflow_job_templates
    - redhat_cop.controller_configuration.users
    - redhat_cop.controller_configuration.teams
    - redhat_cop.controller_configuration.roles  
  post_tasks:
    - name: give demo provisioner team access to new provisioning workflows
      ansible.builtin.include_role:
        name: redhat_cop.controller_configuration.roles
      vars:
        controller_roles:
          - team: Demo Provisioner Team
            role: execute
            workflows: "{{ controller_workflows | community.general.json_query('[*].name') }}"
