---

- name: import validation playbook
  ansible.builtin.import_playbook: validate-selected-demo.yml

- name: remove appropriate configurations from Ansible Controller
  hosts:
    - localhost
  gather_facts: no
  vars:
    controller_state: absent
    resources_path: resources
    controller_resources: "{{ resources_path }}/controller/"
  pre_tasks:
    - name: load in {{ demo }} provisioner vars
      ansible.builtin.include_vars:
        file: "demos/{{ demo }}/vars/provisioner-configuration.yml"
  roles:
    - redhat_cop.controller_configuration.workflow_job_templates
    - redhat_cop.controller_configuration.job_templates
    - redhat_cop.controller_configuration.projects
    - redhat_cop.controller_configuration.inventories
    - redhat_cop.controller_configuration.execution_environments
    - redhat_cop.controller_configuration.credentials
    - redhat_cop.controller_configuration.credential_types
    - redhat_cop.controller_configuration.users
    - redhat_cop.controller_configuration.teams
    - redhat_cop.controller_configuration.organizations

- name: remove common configurations from Ansible Controller when requested
  hosts:
    - localhost
  gather_facts: no
  vars:
    controller_state: absent
  pre_tasks:
    - name: load in preconfigured resources
      ansible.builtin.set_fact:
        controller_organizations: "{{ lookup('file', controller_resources + 'organizations.yml') | from_yaml }}"
        controller_credential_types: "{{ lookup('file', controller_resources + 'credential-types.yml') | from_yaml }}"
        controller_credentials: "{{ lookup('file', controller_resources + 'credentials.yml') | from_yaml }}"
        controller_execution_environments: "{{ lookup('file', controller_resources + 'execution-environments.yml') | from_yaml }}"
        controller_inventories: "{{ lookup('file', controller_resources + 'inventories.yml') | from_yaml }}"
        controller_hosts: "{{ lookup('file', controller_resources + 'hosts.yml') | from_yaml }}"
        controller_groups: "{{ lookup('file', controller_resources + 'groups.yml') | from_yaml }}"
        controller_projects: "{{ lookup('file', controller_resources + 'projects.yml') | from_yaml }}"
        controller_templates: "{{ lookup('file', controller_resources + 'templates.yml') | from_yaml }}"
      when:
        - remove_common_configuration is defined
        - remove_common_configuration
  tasks:
    - name: include roles to remove common provisioner configurations
      ansible.builtin.include_role:
        name: "{{ role }}"
      loop_control:
        loop_var: role
      loop:
        - redhat_cop.controller_configuration.workflow_job_templates
        - redhat_cop.controller_configuration.job_templates
        - redhat_cop.controller_configuration.projects
        - redhat_cop.controller_configuration.inventories
        - redhat_cop.controller_configuration.execution_environments
        - redhat_cop.controller_configuration.credentials
        - redhat_cop.controller_configuration.credential_types
        - redhat_cop.controller_configuration.users
        - redhat_cop.controller_configuration.teams
        - redhat_cop.controller_configuration.organizations
      when:
        - remove_common_configuration is defined
        - remove_common_configuration