---

- name: remove appropriate configurations from Ansible Controller
  hosts:
    - localhost
  gather_facts: no
  vars:
    available_demos:
      - all
      - patching
    deploy_from_controller_org: Default
  pre_tasks:
    - name: validate selected demo is available
      ansible.builtin.assert:
        that:
          - demo in available_demos
        success_msg: "{{ demo }} demo(s) selected"
        fail_msg: "selected demo {{ demo }} is not available, please select one of: {{ available_demos | join(', ') }}"
    - name: include provisioner configuration for {{ demo }} demo
      ansible.builtin.include_vars:
        file: "vars/{{ demo }}/provisioner-configuration.yml"
      when:
        - demo != 'all'
    - name: include provisioner configuration for all demos
      ansible.builtin.include_vars:
        file: "vars/{{ item }}/provisioner-configuration.yml"
      loop: "{{ available_demos }}"
      when:
        - demo == 'all'
        - item != 'all'
  roles:
    - redhat_cop.controller_configuration.workflow_job_templates
    - redhat_cop.controller_configuration.job_templates
    - redhat_cop.controller_configuration.projects
    - redhat_cop.controller_configuration.inventories
    - redhat_cop.controller_configuration.execution_environments
    - redhat_cop.controller_configuration.credentials
    - redhat_cop.controller_configuration.credential_types
