---

- name: import validation playbook
  ansible.builtin.import_playbook: validate-selected-demo.yml

- name: remove appropriate configurations from Ansible Controller
  hosts:
    - localhost
  gather_facts: no
  vars:
    controller_state: absent
  vars_files:
    - "demos/{{ demo }}/vars/provisioner-configuration.yml"
  roles:
    - redhat_cop.controller_configuration.workflow_job_templates
    - redhat_cop.controller_configuration.job_templates
    - redhat_cop.controller_configuration.projects
    - redhat_cop.controller_configuration.inventories
    - redhat_cop.controller_configuration.execution_environments
    - redhat_cop.controller_configuration.credentials
    - redhat_cop.controller_configuration.credential_types
    - redhat_cop.controller_configuration.users
    - redhat_cop.controller_configuration.teams
    - redhat_cop.controller_configuration.organizations

- name: remove common configurations from Ansible Controller when requested
  hosts:
    - localhost
  gather_facts: no
  vars:
    controller_state: absent
  vars_files:
    - demos/common/vars/provisioner-configuration.yml
  tasks:
    - name: include roles to remove common provisioner configurations
      ansible.builtin.include_role:
        name: "{{ role }}"
      loop_control:
        loop_var: role
      loop:
        - redhat_cop.controller_configuration.workflow_job_templates
        - redhat_cop.controller_configuration.job_templates
        - redhat_cop.controller_configuration.projects
        - redhat_cop.controller_configuration.inventories
        - redhat_cop.controller_configuration.execution_environments
        - redhat_cop.controller_configuration.credentials
        - redhat_cop.controller_configuration.credential_types
        - redhat_cop.controller_configuration.users
        - redhat_cop.controller_configuration.teams
        - redhat_cop.controller_configuration.organizations
      when:
        - remove_common_configuration is defined
        - remove_common_configuration