---

- name: remove appropriate configurations from Ansible Controller
  hosts:
    - localhost
  gather_facts: no
  vars_files:
    - vars/demos.yml
  pre_tasks:
    - name: validate selected demo is available
      ansible.builtin.assert:
        that:
          - demo in available_demos
        success_msg: "{{ demo }} demo(s) selected"
        fail_msg: "selected demo {{ demo }} is not available, please select one of: {{ available_demos | join(', ') }}"
    - name: include provisioner configuration for {{ demo }} demo
      ansible.builtin.include_vars:
        file: "vars/{{ demo }}/provisioner-configuration.yml"
  roles:
    - redhat_cop.controller_configuration.workflow_job_templates
    - redhat_cop.controller_configuration.job_templates
    - redhat_cop.controller_configuration.projects
    - redhat_cop.controller_configuration.inventories
    - redhat_cop.controller_configuration.execution_environments
    - redhat_cop.controller_configuration.credentials
    - redhat_cop.controller_configuration.credential_types
