---

controller_hostname: aap20-controller.josh.lab.msp.redhat.com
controller_validate_certs: no
controller_username: admin

controller_organizations:
  - name: "{{ audience }}"
    galaxy_credentials:
      - MSP Lab Automation Hub - RH Certified
      - MSP Lab Automation Hub - Community
      - Ansible Galaxy

controller_credentials:
  - name: Patching Credentials
    credential_type: Machine
    organization: "{{ audience }}"
    inputs:
      username: root
      password: "{{ ansible_password }}"

controller_teams:
  - name: "{{ audience }} Application Team"
    description: application team
    organization: "{{ audience }}"
  - name: "{{ audience }} Infrastructure Team"
    description: infrastructure team
    organization: "{{ audience }}"
  - name: "{{ audience }} Security Team"
    description: security team
    organization: "{{ audience }}"

controller_user_accounts:
  - username: "{{ audience }}_application_team"
    password: "{{ ansible_password }}"
    email: dont@email.me
    update_secrets: no
  - username: "{{ audience }}_infrastructure_team"
    password: "{{ ansible_password }}"
    email: dont@email.me
    update_secrets: no
  - username: "{{ audience }}_security_team"
    password: "{{ ansible_password }}"
    email: dont@email.me
    update_secrets: no

controller_inventories:
  - name: "{{ audience }} Infrastructure"
    organization: "{{ audience }}"

controller_hosts:
  - name: patching-satellite.josh.lab.msp.redhat.com
    inventory: "{{ audience }} Infrastructure"
    variables:
      ansible_host: 10.15.121.1
      satellite:
        username: admin
        password: "{  { ansible_password }}"
        url: https://patching-satellite.demo.lab.msp.redhat.com
        organization: Patching Demo
        composite_content_view: composite-rhel8
        content_view_filter_name: '06-01-2021'
  - name: sapdnhdb1.josh.lab.msp.redhat.com
    inventory: "{{ audience }} Infrastructure"
    variables:
      ansible_host: 10.15.121.31
      ip_address: "{  { ansible_host }}"
      sap_hana_hsr_alias: DC1
  - name: sapdnhdb2.josh.lab.msp.redhat.com
    inventory: "{{ audience }} Infrastructure"
    variables:
      ansible_host: 10.15.121.32
      ip_address: "{  { ansible_host }}"
      sap_hana_hsr_alias: DC2
  - name: sapdnapp1.josh.lab.msp.redhat.com
    inventory: "{{ audience }} Infrastructure"
    variables:
      ansible_host: 10.15.121.34
      ip_address: "{  { ansible_host }}"
  - name: sapdphdb1.josh.lab.msp.redhat.com
    inventory: "{{ audience }} Infrastructure"
    variables:
      ansible_host: 10.15.121.35
      ip_address: "{  { ansible_host }}"
      sap_hana_hsr_alias: DC1
  - name: sapdphdb2.josh.lab.msp.redhat.com
    inventory: "{{ audience }} Infrastructure"
    variables:
      ansible_host: 10.15.121.36
      ip_address: "{  { ansible_host }}"
      sap_hana_hsr_alias: DC2
  - name: sapdpapp1.josh.lab.msp.redhat.com
    inventory: "{{ audience }} Infrastructure"
    variables:
      ansible_host: 10.15.121.38
      ip_address: "{  { ansible_host }}"

controller_groups:
  - name: primary
    inventory: "{{ audience }} Infrastructure"
    hosts:
      - sapdnhdb1.josh.lab.msp.redhat.com
      - sapdphdb1.josh.lab.msp.redhat.com
    variables:
      sap_hana_hsr_role: primary
  - name: secondary
    inventory: "{{ audience }} Infrastructure"
    hosts:
      - sapdnhdb2.josh.lab.msp.redhat.com
      - sapdphdb2.josh.lab.msp.redhat.com
    variables:
      sap_hana_hsr_role: secondary
  - name: hana
    inventory: "{{ audience }} Infrastructure"
    children:
      - primary
      - secondary
    variables:
      cpus: 8
      memory_mb: 73728
  - name: netweaver
    inventory: "{{ audience }} Infrastructure"
    hosts:
      - sapdnapp1.josh.lab.msp.redhat.com
      - sapdpapp1.josh.lab.msp.redhat.com
    variables:
      cpus: 4
      memory_mb: 16384
  - name: sap
    inventory: "{{ audience }} Infrastructure"
    children:
      - hana
      - netweaver
    variables:
      os: rhel8.4
      application: sap
  - name: non_production
    inventory: "{{ audience }} Infrastructure"
    hosts:
      - sapdnapp1.josh.lab.msp.redhat.com
      - sapdnhdb1.josh.lab.msp.redhat.com
      - sapdnhdb2.josh.lab.msp.redhat.com
    variables:
      lifecycle_environment: non_production
  - name: production
    inventory: "{{ audience }} Infrastructure"
    hosts:
      - sapdpapp1.josh.lab.msp.redhat.com
      - sapdphdb1.josh.lab.msp.redhat.com
      - sapdphdb2.josh.lab.msp.redhat.com
    variables:
      lifecycle_environment: production
  - name: kpatch_patch
    inventory: "{{ audience }} Infrastructure"
    children:
      - primary
    variables:
      patching_strategy: kpatch
  - name: normal_patch
    inventory: "{{ audience }} Infrastructure"
    children:
      - netweaver
      - secondary
    variables:
      patching_strategy: normal
  - name: satellite
    inventory: "{{ audience }} Infrastructure"
    hosts:
      - patching-satellite.josh.lab.msp.redhat.com

controller_templates:
  - name: Run Insights Report | Non_Production | Security
    inventory: "{{ audience }} Infrastructure"
    limit: non_production
    project: Patching Demo
    credentials:
      - Patching Credentials
  - name: Check for Updates | Non_Production | Security
    inventory: Patching Demo
    limit: non_production
    project: Patching Demo
    playbook: playbooks/check-for-updates.yml
    credentials:
      - Patching Credentials
  - name: Install Tracer | Non_Production | Infrastructure
    inventory: Patching Demo
    limit: 'non_production:&normal_patch'
    project: Patching Demo
    playbook: playbooks/install-tracer.yml
    credentials:
      - Patching Credentials
  - name: Standby Secondary Database | Non_Production | BASIS (Application Team)
    inventory: Patching Demo
    limit: 'non_production:&secondary'
    project: Patching Demo
    playbook: playbooks/pacemaker-node-control.yml
    credentials:
      - Patching Credentials
    extra_vars:
      pcs_node_status: standby
  - name: Update All Packages | Non_Production | Infrastructure
    inventory: Patching Demo
    limit: 'non_production:&normal_patch'
    project: Patching Demo
    playbook: playbooks/update-all-packates.yml
    credentials:
      - Patching Credentials
  - name: Run Tracer Report | Non_Production | Infrastructure
    inventory: Patching Demo
    limit: 'non_production:&normal_patch'
    project: Patching Demo
    playbook: playbooks/run-tracer-report.yml
    credentials:
      - Patching Credentials
  - name: Reboot Server | Non_Production | Infrastructure
    inventory: Patching Demo
    limit: 'non_production:&normal_patch'
    project: Patching Demo
    playbook: playbooks/reboot-server.yml
    credentials:
      - Patching Credentials  
  - name: Kpatch Server | Non_Production | Infrastructure
    inventory: Patching Demo
    limit: 'non_production:&kpatch'
    project: Patching Demo
    playbook: playbooks/kpatch-server.yml
    credentials:
      - Patching Credentials
  - name: Unstandby Secondary Database | Non_Production | BASIS (Application Team)
    inventory: Patching Demo
    limit: 'non_production:&secondary'
    project: Patching Demo
    playbook: playbooks/pacemaker-node-control.yml
    credentials:
      - Patching Credentials
    extra_vars:
      pcs_node_status: unstandby

controller_workflows:
  - name: Pre-Patching | Non_Production | Security
    organization: "{{ audience }}"
    simplified_workflow_nodes:
      - unified_job_template: Run Insights Report | Non_Production | Security
        identifier: node101
      - unified_job_template: Check for Updates | Non_Production | Security
        identifier: node102
  - name: Pre-Patching | Non_Production | Infrastructure
    organization: "{{ audience }}"
    simplified_workflow_nodes:
      - unified_job_template: Install Tracer | Non_Production | Infrastructure
        identifier: node101
  - name: Pre-Patching | Non_Production | BASIS (Application Team)
    organization: "{{ audience }}"
    simplified_workflow_nodes:
      - unified_job_template: Standby Secondary Database | Non_Production | BASIS (Application Team)
        identifier: node101
  - name: Patching | Non_Production | Infrastructure
    organization: "{{ audience }}"
    simplified_workflow_nodes:
      - unified_job_template: Update All Packages | Non_Production | Infrastructure
        identifier: node101
        success_nodes:
          - node102
      - unified_job_template: Run Tracer Report | Non_Production | Infrastructure
        identifier: node102
        success_nodes:
          - node103
      - unified_job_template: Reboot Server | Non_Production | Infrastructure
        identifier: node103
      - unified_job_template: Kpatch Server | Non_Production | Infrastructure
        identifier: node201
  - name: Post-Patching | Non_Production | Security
    organization: "{{ audience }}"
    simplified_workflow_nodes:
      - unified_job_template: Run Insights Report | Non_Production | Security
        identifier: node101
      - unified_job_template: Check for Updates | Non_Production | Security
        identifier: node102
  - name: Post-Patching | Non_Production | BASIS (Application Team)
    organization: "{{ audience }}"
    simplified_workflow_nodes:
      - unified_job_template: Unstandby Secondary Database | Non_Production | BASIS (Application Team)
        identifier: node101
  - name: Patch Non_Production
    organization: "{{ audience }}"
    simplified_workflow_nodes:
      - unified_job_template: Pre-Patching | Non_Production | Security
        identifier: node101
        success_nodes:
          - node102
      - unified_job_template: Pre-Patching | Non_Production | Infrastructure
        identifier: node102
        success_nodes:
          - node103
      - unified_job_template: Pre-Patching | Non_Production | BASIS (Application Team)
        identifier: node103
        success_nodes:
          - node104
      - unified_job_template: Patching | Non_Production | Infrastructure
        identifier: node104
        success_nodes:
          - node105
      - unified_job_template: Post-Patching | Non_Production | Security
        identifier: node105
        success_nodes:
          - node106
      - unified_job_template: Post-Patching | Non_Production | BASIS (Application Team)
        identifier: node106