---

tower_hostname: patching-tower.demo.lab.msp.redhat.com
tower_validate_certs: no
tower_username: admin
tower_password: "{{ ansible_password }}"

tower_license:
  manifest: files/tower-manifest.zip
  eula_accepted: yes

tower_credentials:
  - name: root
    credential_type: Machine
    organization: Default
    inputs:
      username: root
      password: "{{ ansible_password }}"
  - name: MSP Lab Automation Hub - RH Certified
    credential_type: Ansible Galaxy/Automation Hub API Token
    organization: Default
    inputs:
      url: https://automationhub01.lab.msp.redhat.com/api/galaxy/content/rh-certified/
      token: "{{ automation_hub_token }}"

tower_settings:
  - name: GALAXY_IGNORE_CERTS
    value: true

tower_organizations:
  - name: Default
    galaxy_credentials:
      - MSP Lab Automation Hub - RH Certified

tower_inventories:
  - name: Patching Demo
    organization: Default

tower_hosts:
  - name: patching-satellite.demo.lab.msp.redhat.com
    inventory: Patching Demo
    variables:
      ansible_host: 10.15.121.1
  - name: sapdnhdb1.demo.lab.msp.redhat.com
    inventory: Patching Demo
    variables:
      ansible_host: 10.15.120.31
  - name: sapdphdb1.demo.lab.msp.redhat.com
    inventory: Patching Demo
    variables:
      ansible_host: 10.15.120.33
  - name: sapdnapp1.demo.lab.msp.redhat.com
    inventory: Patching Demo
    variables:
      ansible_host: 10.15.120.32
  - name: sapdpapp1.demo.lab.msp.redhat.com
    inventory: Patching Demo
    variables:
      ansible_host: 10.15.120.34

tower_groups:
  - name: hana
    inventory: Patching Demo
    hosts:
      - sapdnhdb1.demo.lab.msp.redhat.com
      - sapdphdb1.demo.lab.msp.redhat.com
  - name: netweaver
    inventory: Patching Demo
    hosts:
      - sapdnapp1.demo.lab.msp.redhat.com
      - sapdpapp1.demo.lab.msp.redhat.com
  - name: sap
    inventory: Patching Demo
    children:
      - hana
      - netweaver
    variables:
      satellite:
        username: admin
        password: "{{ ansible_password }}"
        url: https://patching-satellite.demo.lab.msp.redhat.com
        organization: Patching Demo
        content_views:
          - name: cv-ansible-rhel8
          - name: cv-appstream-rhel8
          - name: cv-e4s-appstream-rhel8.2
          - name: cv-e4s-highavailability-rhel8.2
          - name: cv-e4s-satellitetools6.9-rhel8.2
          - name: cv-e4s-server-rhel8.2
          - name: cv-kickstart-rhel8.2
          - name: cv-r4h-hana-rhel8.2
          - name: cv-r4s-netweaver-rhel8.2
          - name: cv-satellitetools6.9-rhel8
          - name: cv-server-rhel8
        composite_content_view: composite-rhel8
        content_view_filter_name: '12-31-2020'
  - name: non_production
    inventory: Patching Demo
    hosts:
      - sapdnapp1.demo.lab.msp.redhat.com
      - sapdnhdb1.demo.lab.msp.redhat.com
  - name: production
    inventory: Patching Demo
    hosts:
      - sapdpapp1.demo.lab.msp.redhat.com
      - sapdphdb1.demo.lab.msp.redhat.com
  - name: satellite
    inventory: Patching Demo
    hosts:
      - patching-satellite.demo.lab.msp.redhat.com

tower_projects:
  - name: Patching Demo
    organization: Default
    scm_branch: main
    scm_type: git
    scm_url: https://github.com/jjaswanson4/patching-demo.git
    wait: yes

tower_templates:
  - name: 1 - Run Insights Report
    inventory: Patching Demo
    limit: sap
    project: Patching Demo
    playbook: playbooks/run-insights-report.yml
    credentials:
      - root
  - name: 2 - Check for Updates
    inventory: Patching Demo
    limit: sap
    project: Patching Demo
    playbook: playbooks/check-for-updates.yml
    credentials:
      - root
  - name: 3 - Recheck for Updates
    inventory: Patching Demo
    limit: sap
    project: Patching Demo
    playbook: playbooks/check-for-updates.yml
    credentials:
      - root
  #- name: 4 - Publish New Content
  #  inventory: Patching Demo
  #  limit: satellite
  #  project: Patching Demo
  #  playbook: playbooks/publish-new-content.yml
  - name: 5 - Install Tracer | Netweaver
    inventory: Patching Demo
    limit: netweaver
    project: Patching Demo
    playbook: playbooks/install-tracer.yml
    credentials:
      - root
  - name: 6 - Update All Packages | Netweaver | Non Production
    inventory: Patching Demo
    limit: 'netweaver:&non_production'
    project: Patching Demo
    playbook: playbooks/update-all-packages.yml
    credentials:
      - root
  - name: 7 - kpatch Databases | HANA | Non Production
    inventory: Patching Demo
    limit: 'hana:&non_production'
    project: Patching Demo
    playbook: playbooks/kpatch-server.yml
    credentials:
      - root
  - name: 8 - Run Tracer Report | Netweaver | Non Production
    inventory: Patching Demo
    limit: 'netweaver:&non_production'
    project: Patching Demo
    playbook: playbooks/run-tracer-report.yml
    credentials:
      - root
  - name: 9 - Get Tracer Information | Netweaver | Non Production
    inventory: Patching Demo
    limit: 'netweaver:&non_production'
    project: Patching Demo
    playbook: playbooks/get-tracer-report.yml
    credentials:
      - root
  - name: 10 - Reboot Server | Netweaver | Non Production
    inventory: Patching Demo
    limit: 'netweaver:&non_production'
    project: Patching Demo
    playbook: playbooks/reboot-server.yml
    credentials:
      - root
  - name: 11 - Promote Content to Production
    inventory: Patching Demo
    limit: satellite
    project: Patching Demo
    playbook: playbooks/promote-new-content.yml
  - name: 12 - Check for Updates
    inventory: Patching Demo
    limit: sap
    project: Patching Demo
    playbook: playbooks/check-for-updates.yml
    credentials:
      - root
  - name: 13 - Update All Packages | Netweaver | Production
    inventory: Patching Demo
    limit: 'netweaver:&production'
    project: Patching Demo
    playbook: playbooks/update-all-packages.yml
    credentials:
      - root
  - name: 14 - kpatch Databases | HANA | Production
    inventory: Patching Demo
    limit: 'hana:&production'
    project: Patching Demo
    playbook: playbooks/kpatch-server.yml
    credentials:
      - root
  - name: 15 - Run Tracer Report | Netweaver | Production
    inventory: Patching Demo
    limit: 'netweaver:&production'
    project: Patching Demo
    playbook: playbooks/run-tracer-report.yml
    credentials:
      - root
  - name: 16 - Get Tracer Information | Netweaver | Production
    inventory: Patching Demo
    limit: 'netweaver:&production'
    project: Patching Demo
    playbook: playbooks/get-tracer-report.yml
    credentials:
      - root
  - name: 17 - Reboot Server | Netweaver | Production
    inventory: Patching Demo
    limit: 'netweaver:&production'
    project: Patching Demo
    playbook: playbooks/reboot-server.yml
    credentials:
      - root