---

tower_hostname: automationcontroller-aap20-ansible-automation-platform.apps.ocp4.lab.msp.redhat.com
tower_validate_certs: no
tower_username: admin
tower_password: "{{ tower_password }}"

#tower_license:
#  manifest: files/tower-manifest.zip
#  eula_accepted: yes

tower_credentials:
  - name: Patching Credentials
    credential_type: Machine
    organization: Default
    inputs:
      username: Patching Credentials
      password: "{{ ansible_password }}"
  - name: MSP Lab Automation Hub - RH Certified
    credential_type: Ansible Galaxy/Automation Hub API Token
    organization: Default
    inputs:
      url: https://automationhub01.lab.msp.redhat.com/api/galaxy/content/rh-certified/
      token: "{{ automation_hub_token }}"
    update_secrets: no
  - name: MSP Lab Automation Hub - Community
    credential_type: Ansible Galaxy/Automation Hub API Token
    organization: Default
    inputs:
      url: https://automationhub01.lab.msp.redhat.com/api/galaxy/content/community/
      token: "{{ automation_hub_token }}"
    update_secrets: no

tower_settings:
  - name: GALAXY_IGNORE_CERTS
    value: true

tower_organizations:
  - name: Patching Demo
    galaxy_credentials:
      - MSP Lab Automation Hub - RH Certified

tower_inventories:
  - name: Patching Demo
    organization: Default
    variables:
      satellite:
        username: admin
        password: "{{ ansible_password }}"
        url: https://patching-satellite.demo.lab.msp.redhat.com
        organization: Patching Demo
        composite_content_view: composite-rhel8
        content_view_filter_name: '12-31-2020'
tower_hosts:
  - name: patching-satellite.demo.lab.msp.redhat.com
    inventory: Patching Demo
    variables:
      ansible_host: 10.15.121.1
  - name: sapdnhdb1.demo.lab.msp.redhat.com
    inventory: Patching Demo
    variables:
      ansible_host: 10.15.121.31
  - name: sapdphdb1.demo.lab.msp.redhat.com
    inventory: Patching Demo
    variables:
      ansible_host: 10.15.121.33
  - name: sapdnapp1.demo.lab.msp.redhat.com
    inventory: Patching Demo
    variables:
      ansible_host: 10.15.121.32
  - name: sapdpapp1.demo.lab.msp.redhat.com
    inventory: Patching Demo
    variables:
      ansible_host: 10.15.121.34

tower_groups:
  - name: hana
    inventory: Patching Demo
    hosts:
      - sapdnhdb1.demo.lab.msp.redhat.com
      - sapdphdb1.demo.lab.msp.redhat.com
  - name: netweaver
    inventory: Patching Demo
    hosts:
      - sapdnapp1.demo.lab.msp.redhat.com
      - sapdpapp1.demo.lab.msp.redhat.com
  - name: sap
    inventory: Patching Demo
    children:
      - hana
      - netweaver
  - name: non_production
    inventory: Patching Demo
    hosts:
      - sapdnapp1.demo.lab.msp.redhat.com
      - sapdnhdb1.demo.lab.msp.redhat.com
  - name: production
    inventory: Patching Demo
    hosts:
      - sapdpapp1.demo.lab.msp.redhat.com
      - sapdphdb1.demo.lab.msp.redhat.com
  - name: satellite
    inventory: Patching Demo
    hosts:
      - patching-satellite.demo.lab.msp.redhat.com

tower_projects:
  - name: Patching Demo
    organization: Default
    scm_branch: main
    scm_type: git
    scm_url: https://github.com/jjaswanson4/patching-demo.git
    wait: yes

tower_templates:
  - name: 1 - Run Insights Report
    inventory: Patching Demo
    limit: sap
    project: Patching Demo
    playbook: playbooks/run-insights-report.yml
    credentials:
      - Patching Credentials
  - name: 2 - Check for Updates
    inventory: Patching Demo
    limit: sap
    project: Patching Demo
    playbook: playbooks/check-for-updates.yml
    credentials:
      - Patching Credentials
  - name: 3 - Promote Content | Non_Production
    inventory: Patching Demo
    limit: satellite
    project: Patching Demo
    playbook: playbooks/promote-content.yml
    extra_vars:
      current_lifecycle_environment: Library
      new_lifecycle_environment:
        - Non_Production
  - name: 4 - Recheck for Updates
    inventory: Patching Demo
    limit: sap
    project: Patching Demo
    playbook: playbooks/check-for-updates.yml
    credentials:
      - Patching Credentials
  - name: 5 - Install Tracer | Netweaver
    inventory: Patching Demo
    limit: netweaver
    project: Patching Demo
    playbook: playbooks/install-tracer.yml
    credentials:
      - Patching Credentials
  - name: 6 - Update All Packages | Netweaver | Non Production
    inventory: Patching Demo
    limit: 'netweaver:&non_production'
    project: Patching Demo
    playbook: playbooks/update-all-packages.yml
    credentials:
      - Patching Credentials
  - name: 7 - kpatch Databases | HANA | Non Production
    inventory: Patching Demo
    limit: 'hana:&non_production'
    project: Patching Demo
    playbook: playbooks/kpatch-server.yml
    credentials:
      - Patching Credentials
  - name: 8 - Run Tracer Report | Netweaver | Non Production
    inventory: Patching Demo
    limit: 'netweaver:&non_production'
    project: Patching Demo
    playbook: playbooks/run-tracer-report.yml
    credentials:
      - Patching Credentials
  - name: 9 - Get Tracer Information | Netweaver | Non Production
    inventory: Patching Demo
    limit: 'netweaver:&non_production'
    project: Patching Demo
    playbook: playbooks/get-tracer-report.yml
    credentials:
      - Patching Credentials
  - name: 10 - Reboot Server | Netweaver | Non Production
    inventory: Patching Demo
    limit: 'netweaver:&non_production'
    project: Patching Demo
    playbook: playbooks/reboot-server.yml
    credentials:
      - Patching Credentials
  - name: 11 - Promote Content to Production
    inventory: Patching Demo
    limit: satellite
    project: Patching Demo
    playbook: playbooks/promote-content.yml
    extra_vars:
      current_lifecycle_environment: Non_Production
      new_lifecycle_environment:
        - Production
  - name: 12 - Check for Updates
    inventory: Patching Demo
    limit: sap
    project: Patching Demo
    playbook: playbooks/check-for-updates.yml
    credentials:
      - Patching Credentials
  - name: 13 - Update All Packages | Netweaver | Production
    inventory: Patching Demo
    limit: 'netweaver:&production'
    project: Patching Demo
    playbook: playbooks/update-all-packages.yml
    credentials:
      - Patching Credentials
  - name: 14 - kpatch Databases | HANA | Production
    inventory: Patching Demo
    limit: 'hana:&production'
    project: Patching Demo
    playbook: playbooks/kpatch-server.yml
    credentials:
      - Patching Credentials
  - name: 15 - Run Tracer Report | Netweaver | Production
    inventory: Patching Demo
    limit: 'netweaver:&production'
    project: Patching Demo
    playbook: playbooks/run-tracer-report.yml
    credentials:
      - Patching Credentials
  - name: 16 - Get Tracer Information | Netweaver | Production
    inventory: Patching Demo
    limit: 'netweaver:&production'
    project: Patching Demo
    playbook: playbooks/get-tracer-report.yml
    credentials:
      - Patching Credentials
  - name: 17 - Reboot Server | Netweaver | Production
    inventory: Patching Demo
    limit: 'netweaver:&production'
    project: Patching Demo
    playbook: playbooks/reboot-server.yml
    credentials:
      - Patching Credentials