---

# By default, the org 'Demo Provisioner' is created and resources are configured there,
# Use this variable to override this behavior.
# For example, overriding to 'Default' will put the resources into the default controller organization.
controller_organization: Demo Provisioner

controller_organizations:
  - name: "{{ controller_organization }}"
    galaxy_credentials:
      - MSP Lab Automation Hub - RH Certified
      - MSP Lab Automation Hub - Community
      - Ansible Galaxy

controller_credential_types:
  - name: Demo Provisioner Peripheral Credentials
    kind: cloud
    injectors:
      extra_vars:
        dns_pass: "{{ dns_pass }}"
        ansible_password: "{{ ansible_password }}"
        satellite_password: "{{ satellite_password }}"
        vcenter_password: "{{ vcenter_password }}"
        controller_hostname: "{{ controller_hostname }}"
        controller_username: "{{ controller_username }}"
        controller_password: "{{ controller_password }}"
        controller_validate_certs: "{{ controller_validate_certs }}"

controller_credentials:
  - name: Demo Provisioner Peripheral Credentials
    credential_type: Demo Provisioner Peripheral Credentials
    organization: "{{ controller_organization }}"
  - name: Demo Provisioner Root Account
    credential_type: Machine
    organization: "{{ controller_organization }}"
    inputs:
      username: root
      password: "{{ ansible_password }}"

controller_execution_environments:
  - name: Demo Provisioner EE
    image: aap20-hub.josh.lab.msp.redhat.com/patching-demo-provisioner-ee
    credential: MSP Lab AAP20 Automation Hub
    pull: always

controller_inventories:
  - name: Local Action Inventory
    organization: "{{ controller_organization }}"
    variables:
      ansible_connection: local
      ansible_python_interpreter: '{  { ansible_playbook_python }}'

controller_hosts:
  - name: localhost
    inventory: Local Action Inventory

controller_projects:
  - name: Demo Provisioner Codebase
    organization: "{{ controller_organization }}"
    scm_branch: main
    scm_type: git
    scm_url: https://github.com/jjaswanson4/patching-demo.git
    wait: yes

controller_templates:
  - name: Configure Ansible Controller
    organization: "{{ controller_organization }}"
    inventory: Local Action Inventory
    ask_limit_on_launch: yes
    project: Demo Provisioner Codebase
    allow_simultaneous: yes
    playbook: provisioner/playbooks/configure-ansible-controller.yml
    execution_environment: Demo Provisioner EE
    ask_credential_on_launch: yes
    extra_vars:
      controller_state: present
  - name: Setup Red Hat Satellite
    organization: "{{ controller_organization }}"
    ask_inventory_on_launch: yes
    ask_limit_on_launch: yes
    project: Demo Provisioner Codebase
    allow_simultaneous: yes
    playbook: provisioner/playbooks/deploy-satellite.yml
    execution_environment: Demo Provisioner EE
    ask_credential_on_launch: yes
  - name: Provision Systems
    organization: "{{ controller_organization }}"
    ask_inventory_on_launch: yes
    ask_limit_on_launch: yes
    forks: 10
    project: Demo Provisioner Codebase
    allow_simultaneous: yes
    playbook: provisioner/playbooks/provision-demo-hosts.yml
    execution_environment: Demo Provisioner EE
    ask_credential_on_launch: yes
    extra_vars:
      ansible_become: no
  - name: Preconfigure for SAP
    organization: "{{ controller_organization }}"
    ask_inventory_on_launch: yes
    ask_limit_on_launch: yes
    forks: 10
    project: Demo Provisioner Codebase
    allow_simultaneous: yes
    playbook: provisioner/playbooks/sap-preconfigure.yml
    execution_environment: Demo Provisioner EE
    ask_credential_on_launch: yes
  - name: Preconfigure for HANA
    organization: "{{ controller_organization }}"
    ask_inventory_on_launch: yes
    ask_limit_on_launch: yes
    project: Demo Provisioner Codebase
    allow_simultaneous: yes
    playbook: provisioner/playbooks/hana-preconfigure.yml
    execution_environment: Demo Provisioner EE
    ask_credential_on_launch: yes
  - name: Preconfigure for Netweaver
    organization: "{{ controller_organization }}"
    ask_inventory_on_launch: yes
    ask_limit_on_launch: yes
    project: Demo Provisioner Codebase
    allow_simultaneous: yes
    playbook: provisioner/playbooks/netweaver-preconfigure.yml
    execution_environment: Demo Provisioner EE
    ask_credential_on_launch: yes
  - name: Deploy SAP HANA
    organization: "{{ controller_organization }}"
    ask_inventory_on_launch: yes
    ask_limit_on_launch: yes
    project: Demo Provisioner Codebase
    allow_simultaneous: yes
    playbook: provisioner/playbooks/deploy-hana.yml
    execution_environment: Demo Provisioner EE
    ask_credential_on_launch: yes
  - name: Install Netweaver
    organization: "{{ controller_organization }}"
    ask_inventory_on_launch: yes
    ask_limit_on_launch: yes
    project: Demo Provisioner Codebase
    allow_simultaneous: yes
    playbook: provisioner/playbooks/install-s4.yml
    execution_environment: Demo Provisioner EE
    ask_credential_on_launch: yes
  - name: Reinstate HSR
    organization: "{{ controller_organization }}"
    ask_inventory_on_launch: yes
    ask_limit_on_launch: yes
    project: Demo Provisioner Codebase
    allow_simultaneous: yes
    playbook: provisioner/playbooks/reinstate-hsr.yml
    execution_environment: Demo Provisioner EE
    ask_credential_on_launch: yes
  - name: Remove Controller Configuration
    organization: "{{ controller_organization }}"
    inventory: Local Action Inventory
    ask_limit_on_launch: yes
    project: Demo Provisioner Codebase
    allow_simultaneous: yes
    playbook: provisioner/playbooks/remove-controller-configuration.yml
    execution_environment: Demo Provisioner EE
    ask_credential_on_launch: yes
    extra_vars:
      controller_state: absent
  - name: Unregister from Insights
    organization: "{{ controller_organization }}"
    ask_inventory_on_launch: yes
    ask_limit_on_launch: yes
    forks: 10
    project: Demo Provisioner Codebase
    allow_simultaneous: yes
    playbook: provisioner/playbooks/attempt-insights-unregister.yml
    execution_environment: Demo Provisioner EE
    ask_credential_on_launch: yes
  - name: Teardown Systems
    organization: "{{ controller_organization }}"
    ask_inventory_on_launch: yes
    ask_limit_on_launch: yes
    project: Demo Provisioner Codebase
    allow_simultaneous: yes
    playbook: provisioner/playbooks/teardown-systems.yml
    execution_environment: Demo Provisioner EE
    ask_credential_on_launch: yes
  - name: Cleanup DNS Records
    organization: "{{ controller_organization }}"
    ask_inventory_on_launch: yes
    ask_limit_on_launch: yes
    project: Demo Provisioner Codebase
    allow_simultaneous: yes
    playbook: provisioner/playbooks/delete-dns-records.yml
    execution_environment: Demo Provisioner EE
    ask_credential_on_launch: yes
  - name: Send Provisioner Email | Succeeded
    organization: "{{ controller_organization }}"
    inventory: Local Action Inventory
    limit: localhost
    project: Demo Provisioner Codebase
    allow_simultaneous: yes
    playbook: provisioner/playbooks/send-email.yml
    execution_environment: Demo Provisioner EE
    extra_vars:
      provisioning_status: Succeeded
  - name: Send Provisioner Email | Failed
    organization: "{{ controller_organization }}"
    inventory: Local Action Inventory
    limit: localhost
    project: Demo Provisioner Codebase
    allow_simultaneous: yes
    playbook: provisioner/playbooks/send-email.yml
    execution_environment: Demo Provisioner EE
    extra_vars:
      provisioning_status: Failed

controller_user_accounts:
  - username: demo-admin
    password: "{{ ansible_password }}"
    email: dont@email.me
    update_secrets: no
  - username: demo-provisioner
    password: "{{ ansible_password }}"
    email: dont@email.me
    update_secrets: no  

controller_teams:
  - name: Demo Provisioner Team
    description: Team that can provision demos
    organization: "{{ controller_organization }}"

controller_roles:
  - user: demo-admin
    organization: "{{ controller_organization }}"
    role: admin
  - user: demo-provisioner
    target_team: Demo Provisioner Team
    organization: "{{ controller_organization }}"
    role: member