---

- name: kpatch server
  hosts:
    - all
  tasks:
    - name: get kpatches available for kernel
      ansible.builtin.shell:
        cmd: "yum search kpatch-patch-{{ ansible_kernel | regex_replace('\\.el8.*$', '') | regex_replace('\\.', '_') }} | grep kpatch"
      args:
        warn: no
      check_mode: no
      changed_when: no
      register: kpatches
    - name: list out available kpatches
      ansible.builtin.debug:
        var: kpatches.stdout_lines
    - name: install appropriate kpatch
      ansible.builtin.yum:
        name: "kpatch-patch-{{ ansible_kernel | regex_replace('\\.el8.*$', '') | regex_replace('\\.', '_') }}"
        state: latest